pub const NEXT_CAMERA: &str = &"INPUT_NEXT_CAMERA";
pub const LOOK_LR: &str = &"INPUT_LOOK_LR";
pub const LOOK_UD: &str = &"INPUT_LOOK_UD";
pub const LOOK_UP_ONLY: &str = &"INPUT_LOOK_UP_ONLY";
pub const LOOK_DOWN_ONLY: &str = &"INPUT_LOOK_DOWN_ONLY";
pub const LOOK_LEFT_ONLY: &str = &"INPUT_LOOK_LEFT_ONLY";
pub const LOOK_RIGHT_ONLY: &str = &"INPUT_LOOK_RIGHT_ONLY";
pub const CINEMATIC_SLOWMO: &str = &"INPUT_CINEMATIC_SLOWMO";
pub const SCRIPTED_FLY_UD: &str = &"INPUT_SCRIPTED_FLY_UD";
pub const SCRIPTED_FLY_LR: &str = &"INPUT_SCRIPTED_FLY_LR";
pub const SCRIPTED_FLY_ZUP: &str = &"INPUT_SCRIPTED_FLY_ZUP";
pub const SCRIPTED_FLY_ZDOWN: &str = &"INPUT_SCRIPTED_FLY_ZDOWN";
pub const WEAPON_WHEEL_UD: &str = &"INPUT_WEAPON_WHEEL_UD";
pub const WEAPON_WHEEL_LR: &str = &"INPUT_WEAPON_WHEEL_LR";
pub const WEAPON_WHEEL_NEXT: &str = &"INPUT_WEAPON_WHEEL_NEXT";
pub const WEAPON_WHEEL_PREV: &str = &"INPUT_WEAPON_WHEEL_PREV";
pub const SELECT_NEXT_WEAPON: &str = &"INPUT_SELECT_NEXT_WEAPON";
pub const SELECT_PREV_WEAPON: &str = &"INPUT_SELECT_PREV_WEAPON";
pub const SKIP_CUTSCENE: &str = &"INPUT_SKIP_CUTSCENE";
pub const CHARACTER_WHEEL: &str = &"INPUT_CHARACTER_WHEEL";
pub const MULTIPLAYER_INFO: &str = &"INPUT_MULTIPLAYER_INFO";
pub const SPRINT: &str = &"INPUT_SPRINT";
pub const JUMP: &str = &"INPUT_JUMP";
pub const ENTER: &str = &"INPUT_ENTER";
pub const ATTACK: &str = &"INPUT_ATTACK";
pub const AIM: &str = &"INPUT_AIM";
pub const LOOK_BEHIND: &str = &"INPUT_LOOK_BEHIND";
pub const PHONE: &str = &"INPUT_PHONE";
pub const SPECIAL_ABILITY: &str = &"INPUT_SPECIAL_ABILITY";
pub const SPECIAL_ABILITY_SECONDARY: &str = &"INPUT_SPECIAL_ABILITY_SECONDARY";
pub const MOVE_LR: &str = &"INPUT_MOVE_LR";
pub const MOVE_UD: &str = &"INPUT_MOVE_UD";
pub const MOVE_UP_ONLY: &str = &"INPUT_MOVE_UP_ONLY";
pub const MOVE_DOWN_ONLY: &str = &"INPUT_MOVE_DOWN_ONLY";
pub const MOVE_LEFT_ONLY: &str = &"INPUT_MOVE_LEFT_ONLY";
pub const MOVE_RIGHT_ONLY: &str = &"INPUT_MOVE_RIGHT_ONLY";
pub const DUCK: &str = &"INPUT_DUCK";
pub const SELECT_WEAPON: &str = &"INPUT_SELECT_WEAPON";
pub const PICKUP: &str = &"INPUT_PICKUP";
pub const SNIPER_ZOOM: &str = &"INPUT_SNIPER_ZOOM";
pub const SNIPER_ZOOM_IN_ONLY: &str = &"INPUT_SNIPER_ZOOM_IN_ONLY";
pub const SNIPER_ZOOM_OUT_ONLY: &str = &"INPUT_SNIPER_ZOOM_OUT_ONLY";
pub const SNIPER_ZOOM_IN_SECONDARY: &str = &"INPUT_SNIPER_ZOOM_IN_SECONDARY";
pub const SNIPER_ZOOM_OUT_SECONDARY: &str = &"INPUT_SNIPER_ZOOM_OUT_SECONDARY";
pub const COVER: &str = &"INPUT_COVER";
pub const RELOAD: &str = &"INPUT_RELOAD";
pub const TALK: &str = &"INPUT_TALK";
pub const DETONATE: &str = &"INPUT_DETONATE";
pub const HUD_SPECIAL: &str = &"INPUT_HUD_SPECIAL";
pub const ARREST: &str = &"INPUT_ARREST";
pub const ACCURATE_AIM: &str = &"INPUT_ACCURATE_AIM";
pub const CONTEXT: &str = &"INPUT_CONTEXT";
pub const CONTEXT_SECONDARY: &str = &"INPUT_CONTEXT_SECONDARY";
pub const WEAPON_SPECIAL: &str = &"INPUT_WEAPON_SPECIAL";
pub const WEAPON_SPECIAL_TWO: &str = &"INPUT_WEAPON_SPECIAL_TWO";
pub const DIVE: &str = &"INPUT_DIVE";
pub const DROP_WEAPON: &str = &"INPUT_DROP_WEAPON";
pub const DROP_AMMO: &str = &"INPUT_DROP_AMMO";
pub const THROW_GRENADE: &str = &"INPUT_THROW_GRENADE";
pub const VEH_MOVE_LR: &str = &"INPUT_VEH_MOVE_LR";
pub const VEH_MOVE_UD: &str = &"INPUT_VEH_MOVE_UD";
pub const VEH_MOVE_UP_ONLY: &str = &"INPUT_VEH_MOVE_UP_ONLY";
pub const VEH_MOVE_DOWN_ONLY: &str = &"INPUT_VEH_MOVE_DOWN_ONLY";
pub const VEH_MOVE_LEFT_ONLY: &str = &"INPUT_VEH_MOVE_LEFT_ONLY";
pub const VEH_MOVE_RIGHT_ONLY: &str = &"INPUT_VEH_MOVE_RIGHT_ONLY";
pub const VEH_SPECIAL: &str = &"INPUT_VEH_SPECIAL";
pub const VEH_GUN_LR: &str = &"INPUT_VEH_GUN_LR";
pub const VEH_GUN_UD: &str = &"INPUT_VEH_GUN_UD";
pub const VEH_AIM: &str = &"INPUT_VEH_AIM";
pub const VEH_ATTACK: &str = &"INPUT_VEH_ATTACK";
pub const VEH_ATTACK2: &str = &"INPUT_VEH_ATTACK2";
pub const VEH_ACCELERATE: &str = &"INPUT_VEH_ACCELERATE";
pub const VEH_BRAKE: &str = &"INPUT_VEH_BRAKE";
pub const VEH_DUCK: &str = &"INPUT_VEH_DUCK";
pub const VEH_HEADLIGHT: &str = &"INPUT_VEH_HEADLIGHT";
pub const VEH_EXIT: &str = &"INPUT_VEH_EXIT";
pub const VEH_HANDBRAKE: &str = &"INPUT_VEH_HANDBRAKE";
pub const VEH_HOTWIRE_LEFT: &str = &"INPUT_VEH_HOTWIRE_LEFT";
pub const VEH_HOTWIRE_RIGHT: &str = &"INPUT_VEH_HOTWIRE_RIGHT";
pub const VEH_LOOK_BEHIND: &str = &"INPUT_VEH_LOOK_BEHIND";
pub const VEH_CIN_CAM: &str = &"INPUT_VEH_CIN_CAM";
pub const VEH_NEXT_RADIO: &str = &"INPUT_VEH_NEXT_RADIO";
pub const VEH_PREV_RADIO: &str = &"INPUT_VEH_PREV_RADIO";
pub const VEH_NEXT_RADIO_TRACK: &str = &"INPUT_VEH_NEXT_RADIO_TRACK";
pub const VEH_PREV_RADIO_TRACK: &str = &"INPUT_VEH_PREV_RADIO_TRACK";
pub const VEH_RADIO_WHEEL: &str = &"INPUT_VEH_RADIO_WHEEL";
pub const VEH_HORN: &str = &"INPUT_VEH_HORN";
pub const VEH_FLY_THROTTLE_UP: &str = &"INPUT_VEH_FLY_THROTTLE_UP";
pub const VEH_FLY_THROTTLE_DOWN: &str = &"INPUT_VEH_FLY_THROTTLE_DOWN";
pub const VEH_FLY_YAW_LEFT: &str = &"INPUT_VEH_FLY_YAW_LEFT";
pub const VEH_FLY_YAW_RIGHT: &str = &"INPUT_VEH_FLY_YAW_RIGHT";
pub const VEH_PASSENGER_AIM: &str = &"INPUT_VEH_PASSENGER_AIM";
pub const VEH_PASSENGER_ATTACK: &str = &"INPUT_VEH_PASSENGER_ATTACK";
pub const VEH_SPECIAL_ABILITY_FRANKLIN: &str = &"INPUT_VEH_SPECIAL_ABILITY_FRANKLIN";
pub const VEH_STUNT_UD: &str = &"INPUT_VEH_STUNT_UD";
pub const VEH_CINEMATIC_UD: &str = &"INPUT_VEH_CINEMATIC_UD";
pub const VEH_CINEMATIC_UP_ONLY: &str = &"INPUT_VEH_CINEMATIC_UP_ONLY";
pub const VEH_CINEMATIC_DOWN_ONLY: &str = &"INPUT_VEH_CINEMATIC_DOWN_ONLY";
pub const VEH_CINEMATIC_LR: &str = &"INPUT_VEH_CINEMATIC_LR";
pub const VEH_SELECT_NEXT_WEAPON: &str = &"INPUT_VEH_SELECT_NEXT_WEAPON";
pub const VEH_SELECT_PREV_WEAPON: &str = &"INPUT_VEH_SELECT_PREV_WEAPON";
pub const VEH_ROOF: &str = &"INPUT_VEH_ROOF";
pub const VEH_JUMP: &str = &"INPUT_VEH_JUMP";
pub const VEH_GRAPPLING_HOOK: &str = &"INPUT_VEH_GRAPPLING_HOOK";
pub const VEH_SHUFFLE: &str = &"INPUT_VEH_SHUFFLE";
pub const VEH_DROP_PROJECTILE: &str = &"INPUT_VEH_DROP_PROJECTILE";
pub const VEH_MOUSE_CONTROL_OVERRIDE: &str = &"INPUT_VEH_MOUSE_CONTROL_OVERRIDE";
pub const VEH_FLY_ROLL_LR: &str = &"INPUT_VEH_FLY_ROLL_LR";
pub const VEH_FLY_ROLL_LEFT_ONLY: &str = &"INPUT_VEH_FLY_ROLL_LEFT_ONLY";
pub const VEH_FLY_ROLL_RIGHT_ONLY: &str = &"INPUT_VEH_FLY_ROLL_RIGHT_ONLY";
pub const VEH_FLY_PITCH_UD: &str = &"INPUT_VEH_FLY_PITCH_UD";
pub const VEH_FLY_PITCH_UP_ONLY: &str = &"INPUT_VEH_FLY_PITCH_UP_ONLY";
pub const VEH_FLY_PITCH_DOWN_ONLY: &str = &"INPUT_VEH_FLY_PITCH_DOWN_ONLY";
pub const VEH_FLY_UNDERCARRIAGE: &str = &"INPUT_VEH_FLY_UNDERCARRIAGE";
pub const VEH_FLY_ATTACK: &str = &"INPUT_VEH_FLY_ATTACK";
pub const VEH_FLY_SELECT_NEXT_WEAPON: &str = &"INPUT_VEH_FLY_SELECT_NEXT_WEAPON";
pub const VEH_FLY_SELECT_PREV_WEAPON: &str = &"INPUT_VEH_FLY_SELECT_PREV_WEAPON";
pub const VEH_FLY_SELECT_TARGET_LEFT: &str = &"INPUT_VEH_FLY_SELECT_TARGET_LEFT";
pub const VEH_FLY_SELECT_TARGET_RIGHT: &str = &"INPUT_VEH_FLY_SELECT_TARGET_RIGHT";
pub const VEH_FLY_VERTICAL_FLIGHT_MODE: &str = &"INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE";
pub const VEH_FLY_DUCK: &str = &"INPUT_VEH_FLY_DUCK";
pub const VEH_FLY_ATTACK_CAMERA: &str = &"INPUT_VEH_FLY_ATTACK_CAMERA";
pub const VEH_FLY_MOUSE_CONTROL_OVERRIDE: &str = &"INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE";
pub const VEH_SUB_TURN_LR: &str = &"INPUT_VEH_SUB_TURN_LR";
pub const VEH_SUB_TURN_LEFT_ONLY: &str = &"INPUT_VEH_SUB_TURN_LEFT_ONLY";
pub const VEH_SUB_TURN_RIGHT_ONLY: &str = &"INPUT_VEH_SUB_TURN_RIGHT_ONLY";
pub const VEH_SUB_PITCH_UD: &str = &"INPUT_VEH_SUB_PITCH_UD";
pub const VEH_SUB_PITCH_UP_ONLY: &str = &"INPUT_VEH_SUB_PITCH_UP_ONLY";
pub const VEH_SUB_PITCH_DOWN_ONLY: &str = &"INPUT_VEH_SUB_PITCH_DOWN_ONLY";
pub const VEH_SUB_THROTTLE_UP: &str = &"INPUT_VEH_SUB_THROTTLE_UP";
pub const VEH_SUB_THROTTLE_DOWN: &str = &"INPUT_VEH_SUB_THROTTLE_DOWN";
pub const VEH_SUB_ASCEND: &str = &"INPUT_VEH_SUB_ASCEND";
pub const VEH_SUB_DESCEND: &str = &"INPUT_VEH_SUB_DESCEND";
pub const VEH_SUB_TURN_HARD_LEFT: &str = &"INPUT_VEH_SUB_TURN_HARD_LEFT";
pub const VEH_SUB_TURN_HARD_RIGHT: &str = &"INPUT_VEH_SUB_TURN_HARD_RIGHT";
pub const VEH_SUB_MOUSE_CONTROL_OVERRIDE: &str = &"INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE";
pub const VEH_PUSHBIKE_PEDAL: &str = &"INPUT_VEH_PUSHBIKE_PEDAL";
pub const VEH_PUSHBIKE_SPRINT: &str = &"INPUT_VEH_PUSHBIKE_SPRINT";
pub const VEH_PUSHBIKE_FRONT_BRAKE: &str = &"INPUT_VEH_PUSHBIKE_FRONT_BRAKE";
pub const VEH_PUSHBIKE_REAR_BRAKE: &str = &"INPUT_VEH_PUSHBIKE_REAR_BRAKE";
pub const MELEE_ATTACK_LIGHT: &str = &"INPUT_MELEE_ATTACK_LIGHT";
pub const MELEE_ATTACK_HEAVY: &str = &"INPUT_MELEE_ATTACK_HEAVY";
pub const MELEE_ATTACK_ALTERNATE: &str = &"INPUT_MELEE_ATTACK_ALTERNATE";
pub const MELEE_BLOCK: &str = &"INPUT_MELEE_BLOCK";
pub const PARACHUTE_DEPLOY: &str = &"INPUT_PARACHUTE_DEPLOY";
pub const PARACHUTE_DETACH: &str = &"INPUT_PARACHUTE_DETACH";
pub const PARACHUTE_TURN_LR: &str = &"INPUT_PARACHUTE_TURN_LR";
pub const PARACHUTE_TURN_LEFT_ONLY: &str = &"INPUT_PARACHUTE_TURN_LEFT_ONLY";
pub const PARACHUTE_TURN_RIGHT_ONLY: &str = &"INPUT_PARACHUTE_TURN_RIGHT_ONLY";
pub const PARACHUTE_PITCH_UD: &str = &"INPUT_PARACHUTE_PITCH_UD";
pub const PARACHUTE_PITCH_UP_ONLY: &str = &"INPUT_PARACHUTE_PITCH_UP_ONLY";
pub const PARACHUTE_PITCH_DOWN_ONLY: &str = &"INPUT_PARACHUTE_PITCH_DOWN_ONLY";
pub const PARACHUTE_BRAKE_LEFT: &str = &"INPUT_PARACHUTE_BRAKE_LEFT";
pub const PARACHUTE_BRAKE_RIGHT: &str = &"INPUT_PARACHUTE_BRAKE_RIGHT";
pub const PARACHUTE_SMOKE: &str = &"INPUT_PARACHUTE_SMOKE";
pub const PARACHUTE_PRECISION_LANDING: &str = &"INPUT_PARACHUTE_PRECISION_LANDING";
pub const MAP: &str = &"INPUT_MAP";
pub const SELECT_WEAPON_UNARMED: &str = &"INPUT_SELECT_WEAPON_UNARMED";
pub const SELECT_WEAPON_MELEE: &str = &"INPUT_SELECT_WEAPON_MELEE";
pub const SELECT_WEAPON_HANDGUN: &str = &"INPUT_SELECT_WEAPON_HANDGUN";
pub const SELECT_WEAPON_SHOTGUN: &str = &"INPUT_SELECT_WEAPON_SHOTGUN";
pub const SELECT_WEAPON_SMG: &str = &"INPUT_SELECT_WEAPON_SMG";
pub const SELECT_WEAPON_AUTO_RIFLE: &str = &"INPUT_SELECT_WEAPON_AUTO_RIFLE";
pub const SELECT_WEAPON_SNIPER: &str = &"INPUT_SELECT_WEAPON_SNIPER";
pub const SELECT_WEAPON_HEAVY: &str = &"INPUT_SELECT_WEAPON_HEAVY";
pub const SELECT_WEAPON_SPECIAL: &str = &"INPUT_SELECT_WEAPON_SPECIAL";
pub const SELECT_CHARACTER_MICHAEL: &str = &"INPUT_SELECT_CHARACTER_MICHAEL";
pub const SELECT_CHARACTER_FRANKLIN: &str = &"INPUT_SELECT_CHARACTER_FRANKLIN";
pub const SELECT_CHARACTER_TREVOR: &str = &"INPUT_SELECT_CHARACTER_TREVOR";
pub const SELECT_CHARACTER_MULTIPLAYER: &str = &"INPUT_SELECT_CHARACTER_MULTIPLAYER";
pub const SAVE_REPLAY_CLIP: &str = &"INPUT_SAVE_REPLAY_CLIP";
pub const SPECIAL_ABILITY_PC: &str = &"INPUT_SPECIAL_ABILITY_PC";
pub const CELLPHONE_UP: &str = &"INPUT_CELLPHONE_UP";
pub const CELLPHONE_DOWN: &str = &"INPUT_CELLPHONE_DOWN";
pub const CELLPHONE_LEFT: &str = &"INPUT_CELLPHONE_LEFT";
pub const CELLPHONE_RIGHT: &str = &"INPUT_CELLPHONE_RIGHT";
pub const CELLPHONE_SELECT: &str = &"INPUT_CELLPHONE_SELECT";
pub const CELLPHONE_CANCEL: &str = &"INPUT_CELLPHONE_CANCEL";
pub const CELLPHONE_OPTION: &str = &"INPUT_CELLPHONE_OPTION";
pub const CELLPHONE_EXTRA_OPTION: &str = &"INPUT_CELLPHONE_EXTRA_OPTION";
pub const CELLPHONE_SCROLL_FORWARD: &str = &"INPUT_CELLPHONE_SCROLL_FORWARD";
pub const CELLPHONE_SCROLL_BACKWARD: &str = &"INPUT_CELLPHONE_SCROLL_BACKWARD";
pub const CELLPHONE_CAMERA_FOCUS_LOCK: &str = &"INPUT_CELLPHONE_CAMERA_FOCUS_LOCK";
pub const CELLPHONE_CAMERA_GRID: &str = &"INPUT_CELLPHONE_CAMERA_GRID";
pub const CELLPHONE_CAMERA_SELFIE: &str = &"INPUT_CELLPHONE_CAMERA_SELFIE";
pub const CELLPHONE_CAMERA_DOF: &str = &"INPUT_CELLPHONE_CAMERA_DOF";
pub const CELLPHONE_CAMERA_EXPRESSION: &str = &"INPUT_CELLPHONE_CAMERA_EXPRESSION";
pub const FRONTEND_DOWN: &str = &"INPUT_FRONTEND_DOWN";
pub const FRONTEND_UP: &str = &"INPUT_FRONTEND_UP";
pub const FRONTEND_LEFT: &str = &"INPUT_FRONTEND_LEFT";
pub const FRONTEND_RIGHT: &str = &"INPUT_FRONTEND_RIGHT";
pub const FRONTEND_RDOWN: &str = &"INPUT_FRONTEND_RDOWN";
pub const FRONTEND_RUP: &str = &"INPUT_FRONTEND_RUP";
pub const FRONTEND_RLEFT: &str = &"INPUT_FRONTEND_RLEFT";
pub const FRONTEND_RRIGHT: &str = &"INPUT_FRONTEND_RRIGHT";
pub const FRONTEND_AXIS_X: &str = &"INPUT_FRONTEND_AXIS_X";
pub const FRONTEND_AXIS_Y: &str = &"INPUT_FRONTEND_AXIS_Y";
pub const FRONTEND_RIGHT_AXIS_X: &str = &"INPUT_FRONTEND_RIGHT_AXIS_X";
pub const FRONTEND_RIGHT_AXIS_Y: &str = &"INPUT_FRONTEND_RIGHT_AXIS_Y";
pub const FRONTEND_PAUSE: &str = &"INPUT_FRONTEND_PAUSE";
pub const FRONTEND_PAUSE_ALTERNATE: &str = &"INPUT_FRONTEND_PAUSE_ALTERNATE";
pub const FRONTEND_ACCEPT: &str = &"INPUT_FRONTEND_ACCEPT";
pub const FRONTEND_CANCEL: &str = &"INPUT_FRONTEND_CANCEL";
pub const FRONTEND_X: &str = &"INPUT_FRONTEND_X";
pub const FRONTEND_Y: &str = &"INPUT_FRONTEND_Y";
pub const FRONTEND_LB: &str = &"INPUT_FRONTEND_LB";
pub const FRONTEND_RB: &str = &"INPUT_FRONTEND_RB";
pub const FRONTEND_LT: &str = &"INPUT_FRONTEND_LT";
pub const FRONTEND_RT: &str = &"INPUT_FRONTEND_RT";
pub const FRONTEND_LS: &str = &"INPUT_FRONTEND_LS";
pub const FRONTEND_RS: &str = &"INPUT_FRONTEND_RS";
pub const FRONTEND_LEADERBOARD: &str = &"INPUT_FRONTEND_LEADERBOARD";
pub const FRONTEND_SOCIAL_CLUB: &str = &"INPUT_FRONTEND_SOCIAL_CLUB";
pub const FRONTEND_SOCIAL_CLUB_SECONDARY: &str = &"INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY";
pub const FRONTEND_DELETE: &str = &"INPUT_FRONTEND_DELETE";
pub const FRONTEND_ENDSCREEN_ACCEPT: &str = &"INPUT_FRONTEND_ENDSCREEN_ACCEPT";
pub const FRONTEND_ENDSCREEN_EXPAND: &str = &"INPUT_FRONTEND_ENDSCREEN_EXPAND";
pub const FRONTEND_SELECT: &str = &"INPUT_FRONTEND_SELECT";
pub const SCRIPT_LEFT_AXIS_X: &str = &"INPUT_SCRIPT_LEFT_AXIS_X";
pub const SCRIPT_LEFT_AXIS_Y: &str = &"INPUT_SCRIPT_LEFT_AXIS_Y";
pub const SCRIPT_RIGHT_AXIS_X: &str = &"INPUT_SCRIPT_RIGHT_AXIS_X";
pub const SCRIPT_RIGHT_AXIS_Y: &str = &"INPUT_SCRIPT_RIGHT_AXIS_Y";
pub const SCRIPT_RUP: &str = &"INPUT_SCRIPT_RUP";
pub const SCRIPT_RDOWN: &str = &"INPUT_SCRIPT_RDOWN";
pub const SCRIPT_RLEFT: &str = &"INPUT_SCRIPT_RLEFT";
pub const SCRIPT_RRIGHT: &str = &"INPUT_SCRIPT_RRIGHT";
pub const SCRIPT_LB: &str = &"INPUT_SCRIPT_LB";
pub const SCRIPT_RB: &str = &"INPUT_SCRIPT_RB";
pub const SCRIPT_LT: &str = &"INPUT_SCRIPT_LT";
pub const SCRIPT_RT: &str = &"INPUT_SCRIPT_RT";
pub const SCRIPT_LS: &str = &"INPUT_SCRIPT_LS";
pub const SCRIPT_RS: &str = &"INPUT_SCRIPT_RS";
pub const SCRIPT_PAD_UP: &str = &"INPUT_SCRIPT_PAD_UP";
pub const SCRIPT_PAD_DOWN: &str = &"INPUT_SCRIPT_PAD_DOWN";
pub const SCRIPT_PAD_LEFT: &str = &"INPUT_SCRIPT_PAD_LEFT";
pub const SCRIPT_PAD_RIGHT: &str = &"INPUT_SCRIPT_PAD_RIGHT";
pub const SCRIPT_SELECT: &str = &"INPUT_SCRIPT_SELECT";
pub const CURSOR_ACCEPT: &str = &"INPUT_CURSOR_ACCEPT";
pub const CURSOR_CANCEL: &str = &"INPUT_CURSOR_CANCEL";
pub const CURSOR_X: &str = &"INPUT_CURSOR_X";
pub const CURSOR_Y: &str = &"INPUT_CURSOR_Y";
pub const CURSOR_SCROLL_UP: &str = &"INPUT_CURSOR_SCROLL_UP";
pub const CURSOR_SCROLL_DOWN: &str = &"INPUT_CURSOR_SCROLL_DOWN";
pub const ENTER_CHEAT_CODE: &str = &"INPUT_ENTER_CHEAT_CODE";
pub const INTERACTION_MENU: &str = &"INPUT_INTERACTION_MENU";
pub const MP_TEXT_CHAT_ALL: &str = &"INPUT_MP_TEXT_CHAT_ALL";
pub const MP_TEXT_CHAT_TEAM: &str = &"INPUT_MP_TEXT_CHAT_TEAM";
pub const MP_TEXT_CHAT_FRIENDS: &str = &"INPUT_MP_TEXT_CHAT_FRIENDS";
pub const MP_TEXT_CHAT_CREW: &str = &"INPUT_MP_TEXT_CHAT_CREW";
pub const PUSH_TO_TALK: &str = &"INPUT_PUSH_TO_TALK";
pub const CREATOR_LS: &str = &"INPUT_CREATOR_LS";
pub const CREATOR_RS: &str = &"INPUT_CREATOR_RS";
pub const CREATOR_LT: &str = &"INPUT_CREATOR_LT";
pub const CREATOR_RT: &str = &"INPUT_CREATOR_RT";
pub const CREATOR_MENU_TOGGLE: &str = &"INPUT_CREATOR_MENU_TOGGLE";
pub const CREATOR_ACCEPT: &str = &"INPUT_CREATOR_ACCEPT";
pub const CREATOR_DELETE: &str = &"INPUT_CREATOR_DELETE";
pub const ATTACK2: &str = &"INPUT_ATTACK2";
pub const RAPPEL_JUMP: &str = &"INPUT_RAPPEL_JUMP";
pub const RAPPEL_LONG_JUMP: &str = &"INPUT_RAPPEL_LONG_JUMP";
pub const RAPPEL_SMASH_WINDOW: &str = &"INPUT_RAPPEL_SMASH_WINDOW";
pub const PREV_WEAPON: &str = &"INPUT_PREV_WEAPON";
pub const NEXT_WEAPON: &str = &"INPUT_NEXT_WEAPON";
pub const MELEE_ATTACK1: &str = &"INPUT_MELEE_ATTACK1";
pub const MELEE_ATTACK2: &str = &"INPUT_MELEE_ATTACK2";
pub const WHISTLE: &str = &"INPUT_WHISTLE";
pub const MOVE_LEFT: &str = &"INPUT_MOVE_LEFT";
pub const MOVE_RIGHT: &str = &"INPUT_MOVE_RIGHT";
pub const MOVE_UP: &str = &"INPUT_MOVE_UP";
pub const MOVE_DOWN: &str = &"INPUT_MOVE_DOWN";
pub const LOOK_LEFT: &str = &"INPUT_LOOK_LEFT";
pub const LOOK_RIGHT: &str = &"INPUT_LOOK_RIGHT";
pub const LOOK_UP: &str = &"INPUT_LOOK_UP";
pub const LOOK_DOWN: &str = &"INPUT_LOOK_DOWN";
pub const SNIPER_ZOOM_IN: &str = &"INPUT_SNIPER_ZOOM_IN";
pub const SNIPER_ZOOM_OUT: &str = &"INPUT_SNIPER_ZOOM_OUT";
pub const SNIPER_ZOOM_IN_ALTERNATE: &str = &"INPUT_SNIPER_ZOOM_IN_ALTERNATE";
pub const SNIPER_ZOOM_OUT_ALTERNATE: &str = &"INPUT_SNIPER_ZOOM_OUT_ALTERNATE";
pub const VEH_MOVE_LEFT: &str = &"INPUT_VEH_MOVE_LEFT";
pub const VEH_MOVE_RIGHT: &str = &"INPUT_VEH_MOVE_RIGHT";
pub const VEH_MOVE_UP: &str = &"INPUT_VEH_MOVE_UP";
pub const VEH_MOVE_DOWN: &str = &"INPUT_VEH_MOVE_DOWN";
pub const VEH_GUN_LEFT: &str = &"INPUT_VEH_GUN_LEFT";
pub const VEH_GUN_RIGHT: &str = &"INPUT_VEH_GUN_RIGHT";
pub const VEH_GUN_UP: &str = &"INPUT_VEH_GUN_UP";
pub const VEH_GUN_DOWN: &str = &"INPUT_VEH_GUN_DOWN";
pub const VEH_LOOK_LEFT: &str = &"INPUT_VEH_LOOK_LEFT";
pub const VEH_LOOK_RIGHT: &str = &"INPUT_VEH_LOOK_RIGHT";
pub const REPLAY_START_STOP_RECORDING: &str = &"INPUT_REPLAY_START_STOP_RECORDING";
pub const REPLAY_START_STOP_RECORDING_SECONDARY: &str = &"INPUT_REPLAY_START_STOP_RECORDING_SECONDARY";
pub const SCALED_LOOK_LR: &str = &"INPUT_SCALED_LOOK_LR";
pub const SCALED_LOOK_UD: &str = &"INPUT_SCALED_LOOK_UD";
pub const SCALED_LOOK_UP_ONLY: &str = &"INPUT_SCALED_LOOK_UP_ONLY";
pub const SCALED_LOOK_DOWN_ONLY: &str = &"INPUT_SCALED_LOOK_DOWN_ONLY";
pub const SCALED_LOOK_LEFT_ONLY: &str = &"INPUT_SCALED_LOOK_LEFT_ONLY";
pub const SCALED_LOOK_RIGHT_ONLY: &str = &"INPUT_SCALED_LOOK_RIGHT_ONLY";
pub const REPLAY_MARKER_DELETE: &str = &"INPUT_REPLAY_MARKER_DELETE";
pub const REPLAY_CLIP_DELETE: &str = &"INPUT_REPLAY_CLIP_DELETE";
pub const REPLAY_PAUSE: &str = &"INPUT_REPLAY_PAUSE";
pub const REPLAY_REWIND: &str = &"INPUT_REPLAY_REWIND";
pub const REPLAY_FFWD: &str = &"INPUT_REPLAY_FFWD";
pub const REPLAY_NEWMARKER: &str = &"INPUT_REPLAY_NEWMARKER";
pub const REPLAY_RECORD: &str = &"INPUT_REPLAY_RECORD";
pub const REPLAY_SCREENSHOT: &str = &"INPUT_REPLAY_SCREENSHOT";
pub const REPLAY_HIDEHUD: &str = &"INPUT_REPLAY_HIDEHUD";
pub const REPLAY_STARTPOINT: &str = &"INPUT_REPLAY_STARTPOINT";
pub const REPLAY_ENDPOINT: &str = &"INPUT_REPLAY_ENDPOINT";
pub const REPLAY_ADVANCE: &str = &"INPUT_REPLAY_ADVANCE";
pub const REPLAY_BACK: &str = &"INPUT_REPLAY_BACK";
pub const REPLAY_TOOLS: &str = &"INPUT_REPLAY_TOOLS";
pub const REPLAY_RESTART: &str = &"INPUT_REPLAY_RESTART";
pub const REPLAY_SHOWHOTKEY: &str = &"INPUT_REPLAY_SHOWHOTKEY";
pub const REPLAY_CYCLEMARKERLEFT: &str = &"INPUT_REPLAY_CYCLEMARKERLEFT";
pub const REPLAY_CYCLEMARKERRIGHT: &str = &"INPUT_REPLAY_CYCLEMARKERRIGHT";
pub const REPLAY_FOVINCREASE: &str = &"INPUT_REPLAY_FOVINCREASE";
pub const REPLAY_FOVDECREASE: &str = &"INPUT_REPLAY_FOVDECREASE";
pub const REPLAY_CAMERAUP: &str = &"INPUT_REPLAY_CAMERAUP";
pub const REPLAY_CAMERADOWN: &str = &"INPUT_REPLAY_CAMERADOWN";
pub const REPLAY_SAVE: &str = &"INPUT_REPLAY_SAVE";
pub const REPLAY_TOGGLETIME: &str = &"INPUT_REPLAY_TOGGLETIME";
pub const REPLAY_TOGGLETIPS: &str = &"INPUT_REPLAY_TOGGLETIPS";
pub const REPLAY_PREVIEW: &str = &"INPUT_REPLAY_PREVIEW";
pub const REPLAY_TOGGLE_TIMELINE: &str = &"INPUT_REPLAY_TOGGLE_TIMELINE";
pub const REPLAY_TIMELINE_PICKUP_CLIP: &str = &"INPUT_REPLAY_TIMELINE_PICKUP_CLIP";
pub const REPLAY_TIMELINE_DUPLICATE_CLIP: &str = &"INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP";
pub const REPLAY_TIMELINE_PLACE_CLIP: &str = &"INPUT_REPLAY_TIMELINE_PLACE_CLIP";
pub const REPLAY_CTRL: &str = &"INPUT_REPLAY_CTRL";
pub const REPLAY_TIMELINE_SAVE: &str = &"INPUT_REPLAY_TIMELINE_SAVE";
pub const REPLAY_PREVIEW_AUDIO: &str = &"INPUT_REPLAY_PREVIEW_AUDIO";
pub const VEH_DRIVE_LOOK: &str = &"INPUT_VEH_DRIVE_LOOK";
pub const VEH_DRIVE_LOOK2: &str = &"INPUT_VEH_DRIVE_LOOK2";
pub const VEH_FLY_ATTACK2: &str = &"INPUT_VEH_FLY_ATTACK2";
pub const RADIO_WHEEL_UD: &str = &"INPUT_RADIO_WHEEL_UD";
pub const RADIO_WHEEL_LR: &str = &"INPUT_RADIO_WHEEL_LR";
pub const VEH_SLOWMO_UD: &str = &"INPUT_VEH_SLOWMO_UD";
pub const VEH_SLOWMO_UP_ONLY: &str = &"INPUT_VEH_SLOWMO_UP_ONLY";
pub const VEH_SLOWMO_DOWN_ONLY: &str = &"INPUT_VEH_SLOWMO_DOWN_ONLY";
pub const VEH_HYDRAULICS_CONTROL_TOGGLE: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE";
pub const VEH_HYDRAULICS_CONTROL_LEFT: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_LEFT";
pub const VEH_HYDRAULICS_CONTROL_RIGHT: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_RIGHT";
pub const VEH_HYDRAULICS_CONTROL_UP: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_UP";
pub const VEH_HYDRAULICS_CONTROL_DOWN: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_DOWN";
pub const VEH_HYDRAULICS_CONTROL_UD: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_UD";
pub const VEH_HYDRAULICS_CONTROL_LR: &str = &"INPUT_VEH_HYDRAULICS_CONTROL_LR";
pub const SWITCH_VISOR: &str = &"INPUT_SWITCH_VISOR";
pub const VEH_MELEE_HOLD: &str = &"INPUT_VEH_MELEE_HOLD";
pub const VEH_MELEE_LEFT: &str = &"INPUT_VEH_MELEE_LEFT";
pub const VEH_MELEE_RIGHT: &str = &"INPUT_VEH_MELEE_RIGHT";
pub const MAP_POI: &str = &"INPUT_MAP_POI";
pub const REPLAY_SNAPMATIC_PHOTO: &str = &"INPUT_REPLAY_SNAPMATIC_PHOTO";
pub const VEH_CAR_JUMP: &str = &"INPUT_VEH_CAR_JUMP";
pub const VEH_ROCKET_BOOST: &str = &"INPUT_VEH_ROCKET_BOOST";
pub const VEH_FLY_BOOST: &str = &"INPUT_VEH_FLY_BOOST";
pub const VEH_PARACHUTE: &str = &"INPUT_VEH_PARACHUTE";
pub const VEH_BIKE_WINGS: &str = &"INPUT_VEH_BIKE_WINGS";
pub const VEH_FLY_BOMB_BAY: &str = &"INPUT_VEH_FLY_BOMB_BAY";
pub const VEH_FLY_COUNTER: &str = &"INPUT_VEH_FLY_COUNTER";
pub const VEH_TRANSFORM: &str = &"INPUT_VEH_TRANSFORM";
pub const QUAD_LOCO_REVERSE: &str = &"INPUT_QUAD_LOCO_REVERSE";
pub const RESPAWN_FASTER: &str = &"INPUT_RESPAWN_FASTER";
pub const HUDMARKER_SELECT: &str = &"INPUT_HUDMARKER_SELECT";

pub const ALL: &[&str] = &[
    NEXT_CAMERA,
    LOOK_LR,
    LOOK_UD,
    LOOK_UP_ONLY,
    LOOK_DOWN_ONLY,
    LOOK_LEFT_ONLY,
    LOOK_RIGHT_ONLY,
    CINEMATIC_SLOWMO,
    SCRIPTED_FLY_UD,
    SCRIPTED_FLY_LR,
    SCRIPTED_FLY_ZUP,
    SCRIPTED_FLY_ZDOWN,
    WEAPON_WHEEL_UD,
    WEAPON_WHEEL_LR,
    WEAPON_WHEEL_NEXT,
    WEAPON_WHEEL_PREV,
    SELECT_NEXT_WEAPON,
    SELECT_PREV_WEAPON,
    SKIP_CUTSCENE,
    CHARACTER_WHEEL,
    MULTIPLAYER_INFO,
    SPRINT,
    JUMP,
    ENTER,
    ATTACK,
    AIM,
    LOOK_BEHIND,
    PHONE,
    SPECIAL_ABILITY,
    SPECIAL_ABILITY_SECONDARY,
    MOVE_LR,
    MOVE_UD,
    MOVE_UP_ONLY,
    MOVE_DOWN_ONLY,
    MOVE_LEFT_ONLY,
    MOVE_RIGHT_ONLY,
    DUCK,
    SELECT_WEAPON,
    PICKUP,
    SNIPER_ZOOM,
    SNIPER_ZOOM_IN_ONLY,
    SNIPER_ZOOM_OUT_ONLY,
    SNIPER_ZOOM_IN_SECONDARY,
    SNIPER_ZOOM_OUT_SECONDARY,
    COVER,
    RELOAD,
    TALK,
    DETONATE,
    HUD_SPECIAL,
    ARREST,
    ACCURATE_AIM,
    CONTEXT,
    CONTEXT_SECONDARY,
    WEAPON_SPECIAL,
    WEAPON_SPECIAL_TWO,
    DIVE,
    DROP_WEAPON,
    DROP_AMMO,
    THROW_GRENADE,
    VEH_MOVE_LR,
    VEH_MOVE_UD,
    VEH_MOVE_UP_ONLY,
    VEH_MOVE_DOWN_ONLY,
    VEH_MOVE_LEFT_ONLY,
    VEH_MOVE_RIGHT_ONLY,
    VEH_SPECIAL,
    VEH_GUN_LR,
    VEH_GUN_UD,
    VEH_AIM,
    VEH_ATTACK,
    VEH_ATTACK2,
    VEH_ACCELERATE,
    VEH_BRAKE,
    VEH_DUCK,
    VEH_HEADLIGHT,
    VEH_EXIT,
    VEH_HANDBRAKE,
    VEH_HOTWIRE_LEFT,
    VEH_HOTWIRE_RIGHT,
    VEH_LOOK_BEHIND,
    VEH_CIN_CAM,
    VEH_NEXT_RADIO,
    VEH_PREV_RADIO,
    VEH_NEXT_RADIO_TRACK,
    VEH_PREV_RADIO_TRACK,
    VEH_RADIO_WHEEL,
    VEH_HORN,
    VEH_FLY_THROTTLE_UP,
    VEH_FLY_THROTTLE_DOWN,
    VEH_FLY_YAW_LEFT,
    VEH_FLY_YAW_RIGHT,
    VEH_PASSENGER_AIM,
    VEH_PASSENGER_ATTACK,
    VEH_SPECIAL_ABILITY_FRANKLIN,
    VEH_STUNT_UD,
    VEH_CINEMATIC_UD,
    VEH_CINEMATIC_UP_ONLY,
    VEH_CINEMATIC_DOWN_ONLY,
    VEH_CINEMATIC_LR,
    VEH_SELECT_NEXT_WEAPON,
    VEH_SELECT_PREV_WEAPON,
    VEH_ROOF,
    VEH_JUMP,
    VEH_GRAPPLING_HOOK,
    VEH_SHUFFLE,
    VEH_DROP_PROJECTILE,
    VEH_MOUSE_CONTROL_OVERRIDE,
    VEH_FLY_ROLL_LR,
    VEH_FLY_ROLL_LEFT_ONLY,
    VEH_FLY_ROLL_RIGHT_ONLY,
    VEH_FLY_PITCH_UD,
    VEH_FLY_PITCH_UP_ONLY,
    VEH_FLY_PITCH_DOWN_ONLY,
    VEH_FLY_UNDERCARRIAGE,
    VEH_FLY_ATTACK,
    VEH_FLY_SELECT_NEXT_WEAPON,
    VEH_FLY_SELECT_PREV_WEAPON,
    VEH_FLY_SELECT_TARGET_LEFT,
    VEH_FLY_SELECT_TARGET_RIGHT,
    VEH_FLY_VERTICAL_FLIGHT_MODE,
    VEH_FLY_DUCK,
    VEH_FLY_ATTACK_CAMERA,
    VEH_FLY_MOUSE_CONTROL_OVERRIDE,
    VEH_SUB_TURN_LR,
    VEH_SUB_TURN_LEFT_ONLY,
    VEH_SUB_TURN_RIGHT_ONLY,
    VEH_SUB_PITCH_UD,
    VEH_SUB_PITCH_UP_ONLY,
    VEH_SUB_PITCH_DOWN_ONLY,
    VEH_SUB_THROTTLE_UP,
    VEH_SUB_THROTTLE_DOWN,
    VEH_SUB_ASCEND,
    VEH_SUB_DESCEND,
    VEH_SUB_TURN_HARD_LEFT,
    VEH_SUB_TURN_HARD_RIGHT,
    VEH_SUB_MOUSE_CONTROL_OVERRIDE,
    VEH_PUSHBIKE_PEDAL,
    VEH_PUSHBIKE_SPRINT,
    VEH_PUSHBIKE_FRONT_BRAKE,
    VEH_PUSHBIKE_REAR_BRAKE,
    MELEE_ATTACK_LIGHT,
    MELEE_ATTACK_HEAVY,
    MELEE_ATTACK_ALTERNATE,
    MELEE_BLOCK,
    PARACHUTE_DEPLOY,
    PARACHUTE_DETACH,
    PARACHUTE_TURN_LR,
    PARACHUTE_TURN_LEFT_ONLY,
    PARACHUTE_TURN_RIGHT_ONLY,
    PARACHUTE_PITCH_UD,
    PARACHUTE_PITCH_UP_ONLY,
    PARACHUTE_PITCH_DOWN_ONLY,
    PARACHUTE_BRAKE_LEFT,
    PARACHUTE_BRAKE_RIGHT,
    PARACHUTE_SMOKE,
    PARACHUTE_PRECISION_LANDING,
    MAP,
    SELECT_WEAPON_UNARMED,
    SELECT_WEAPON_MELEE,
    SELECT_WEAPON_HANDGUN,
    SELECT_WEAPON_SHOTGUN,
    SELECT_WEAPON_SMG,
    SELECT_WEAPON_AUTO_RIFLE,
    SELECT_WEAPON_SNIPER,
    SELECT_WEAPON_HEAVY,
    SELECT_WEAPON_SPECIAL,
    SELECT_CHARACTER_MICHAEL,
    SELECT_CHARACTER_FRANKLIN,
    SELECT_CHARACTER_TREVOR,
    SELECT_CHARACTER_MULTIPLAYER,
    SAVE_REPLAY_CLIP,
    SPECIAL_ABILITY_PC,
    CELLPHONE_UP,
    CELLPHONE_DOWN,
    CELLPHONE_LEFT,
    CELLPHONE_RIGHT,
    CELLPHONE_SELECT,
    CELLPHONE_CANCEL,
    CELLPHONE_OPTION,
    CELLPHONE_EXTRA_OPTION,
    CELLPHONE_SCROLL_FORWARD,
    CELLPHONE_SCROLL_BACKWARD,
    CELLPHONE_CAMERA_FOCUS_LOCK,
    CELLPHONE_CAMERA_GRID,
    CELLPHONE_CAMERA_SELFIE,
    CELLPHONE_CAMERA_DOF,
    CELLPHONE_CAMERA_EXPRESSION,
    FRONTEND_DOWN,
    FRONTEND_UP,
    FRONTEND_LEFT,
    FRONTEND_RIGHT,
    FRONTEND_RDOWN,
    FRONTEND_RUP,
    FRONTEND_RLEFT,
    FRONTEND_RRIGHT,
    FRONTEND_AXIS_X,
    FRONTEND_AXIS_Y,
    FRONTEND_RIGHT_AXIS_X,
    FRONTEND_RIGHT_AXIS_Y,
    FRONTEND_PAUSE,
    FRONTEND_PAUSE_ALTERNATE,
    FRONTEND_ACCEPT,
    FRONTEND_CANCEL,
    FRONTEND_X,
    FRONTEND_Y,
    FRONTEND_LB,
    FRONTEND_RB,
    FRONTEND_LT,
    FRONTEND_RT,
    FRONTEND_LS,
    FRONTEND_RS,
    FRONTEND_LEADERBOARD,
    FRONTEND_SOCIAL_CLUB,
    FRONTEND_SOCIAL_CLUB_SECONDARY,
    FRONTEND_DELETE,
    FRONTEND_ENDSCREEN_ACCEPT,
    FRONTEND_ENDSCREEN_EXPAND,
    FRONTEND_SELECT,
    SCRIPT_LEFT_AXIS_X,
    SCRIPT_LEFT_AXIS_Y,
    SCRIPT_RIGHT_AXIS_X,
    SCRIPT_RIGHT_AXIS_Y,
    SCRIPT_RUP,
    SCRIPT_RDOWN,
    SCRIPT_RLEFT,
    SCRIPT_RRIGHT,
    SCRIPT_LB,
    SCRIPT_RB,
    SCRIPT_LT,
    SCRIPT_RT,
    SCRIPT_LS,
    SCRIPT_RS,
    SCRIPT_PAD_UP,
    SCRIPT_PAD_DOWN,
    SCRIPT_PAD_LEFT,
    SCRIPT_PAD_RIGHT,
    SCRIPT_SELECT,
    CURSOR_ACCEPT,
    CURSOR_CANCEL,
    CURSOR_X,
    CURSOR_Y,
    CURSOR_SCROLL_UP,
    CURSOR_SCROLL_DOWN,
    ENTER_CHEAT_CODE,
    INTERACTION_MENU,
    MP_TEXT_CHAT_ALL,
    MP_TEXT_CHAT_TEAM,
    MP_TEXT_CHAT_FRIENDS,
    MP_TEXT_CHAT_CREW,
    PUSH_TO_TALK,
    CREATOR_LS,
    CREATOR_RS,
    CREATOR_LT,
    CREATOR_RT,
    CREATOR_MENU_TOGGLE,
    CREATOR_ACCEPT,
    CREATOR_DELETE,
    ATTACK2,
    RAPPEL_JUMP,
    RAPPEL_LONG_JUMP,
    RAPPEL_SMASH_WINDOW,
    PREV_WEAPON,
    NEXT_WEAPON,
    MELEE_ATTACK1,
    MELEE_ATTACK2,
    WHISTLE,
    MOVE_LEFT,
    MOVE_RIGHT,
    MOVE_UP,
    MOVE_DOWN,
    LOOK_LEFT,
    LOOK_RIGHT,
    LOOK_UP,
    LOOK_DOWN,
    SNIPER_ZOOM_IN,
    SNIPER_ZOOM_OUT,
    SNIPER_ZOOM_IN_ALTERNATE,
    SNIPER_ZOOM_OUT_ALTERNATE,
    VEH_MOVE_LEFT,
    VEH_MOVE_RIGHT,
    VEH_MOVE_UP,
    VEH_MOVE_DOWN,
    VEH_GUN_LEFT,
    VEH_GUN_RIGHT,
    VEH_GUN_UP,
    VEH_GUN_DOWN,
    VEH_LOOK_LEFT,
    VEH_LOOK_RIGHT,
    REPLAY_START_STOP_RECORDING,
    REPLAY_START_STOP_RECORDING_SECONDARY,
    SCALED_LOOK_LR,
    SCALED_LOOK_UD,
    SCALED_LOOK_UP_ONLY,
    SCALED_LOOK_DOWN_ONLY,
    SCALED_LOOK_LEFT_ONLY,
    SCALED_LOOK_RIGHT_ONLY,
    REPLAY_MARKER_DELETE,
    REPLAY_CLIP_DELETE,
    REPLAY_PAUSE,
    REPLAY_REWIND,
    REPLAY_FFWD,
    REPLAY_NEWMARKER,
    REPLAY_RECORD,
    REPLAY_SCREENSHOT,
    REPLAY_HIDEHUD,
    REPLAY_STARTPOINT,
    REPLAY_ENDPOINT,
    REPLAY_ADVANCE,
    REPLAY_BACK,
    REPLAY_TOOLS,
    REPLAY_RESTART,
    REPLAY_SHOWHOTKEY,
    REPLAY_CYCLEMARKERLEFT,
    REPLAY_CYCLEMARKERRIGHT,
    REPLAY_FOVINCREASE,
    REPLAY_FOVDECREASE,
    REPLAY_CAMERAUP,
    REPLAY_CAMERADOWN,
    REPLAY_SAVE,
    REPLAY_TOGGLETIME,
    REPLAY_TOGGLETIPS,
    REPLAY_PREVIEW,
    REPLAY_TOGGLE_TIMELINE,
    REPLAY_TIMELINE_PICKUP_CLIP,
    REPLAY_TIMELINE_DUPLICATE_CLIP,
    REPLAY_TIMELINE_PLACE_CLIP,
    REPLAY_CTRL,
    REPLAY_TIMELINE_SAVE,
    REPLAY_PREVIEW_AUDIO,
    VEH_DRIVE_LOOK,
    VEH_DRIVE_LOOK2,
    VEH_FLY_ATTACK2,
    RADIO_WHEEL_UD,
    RADIO_WHEEL_LR,
    VEH_SLOWMO_UD,
    VEH_SLOWMO_UP_ONLY,
    VEH_SLOWMO_DOWN_ONLY,
    VEH_HYDRAULICS_CONTROL_TOGGLE,
    VEH_HYDRAULICS_CONTROL_LEFT,
    VEH_HYDRAULICS_CONTROL_RIGHT,
    VEH_HYDRAULICS_CONTROL_UP,
    VEH_HYDRAULICS_CONTROL_DOWN,
    VEH_HYDRAULICS_CONTROL_UD,
    VEH_HYDRAULICS_CONTROL_LR,
    SWITCH_VISOR,
    VEH_MELEE_HOLD,
    VEH_MELEE_LEFT,
    VEH_MELEE_RIGHT,
    MAP_POI,
    REPLAY_SNAPMATIC_PHOTO,
    VEH_CAR_JUMP,
    VEH_ROCKET_BOOST,
    VEH_FLY_BOOST,
    VEH_PARACHUTE,
    VEH_BIKE_WINGS,
    VEH_FLY_BOMB_BAY,
    VEH_FLY_COUNTER,
    VEH_TRANSFORM,
    QUAD_LOCO_REVERSE,
    RESPAWN_FASTER,
    HUDMARKER_SELECT,
];