pub const CATEGORY: &'static str = &"CELLPHONE_MISC";
pub const CELLPHONE_SELECT: &'static str = &"INPUT_CELLPHONE_SELECT";
pub const CELLPHONE_CANCEL: &'static str = &"INPUT_CELLPHONE_CANCEL";
pub const CELLPHONE_OPTION: &'static str = &"INPUT_CELLPHONE_OPTION";
pub const CELLPHONE_EXTRA_OPTION: &'static str = &"INPUT_CELLPHONE_EXTRA_OPTION";
pub const CELLPHONE_SCROLL_FORWARD: &'static str = &"INPUT_CELLPHONE_SCROLL_FORWARD";
pub const CELLPHONE_SCROLL_BACKWARD: &'static str = &"INPUT_CELLPHONE_SCROLL_BACKWARD";
