pub const CATEGORY: &'static str = &"CELLPHONE_CAMERA";
pub const CELLPHONE_CAMERA_SELFIE : &'static str = &"INPUT_CELLPHONE_CAMERA_SELFIE ";
pub const CELLPHONE_CAMERA_EXPRESSION: &'static str = &"INPUT_CELLPHONE_CAMERA_EXPRESSION";
pub const CELLPHONE_CAMERA_GRID: &'static str = &"INPUT_CELLPHONE_CAMERA_GRID";
pub const CELLPHONE_CAMERA_DOF: &'static str = &"INPUT_CELLPHONE_CAMERA_DOF";
pub const CELLPHONE_CAMERA_FOCUS_LOCK: &'static str = &"INPUT_CELLPHONE_CAMERA_FOCUS_LOCK";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // CELLPHONE_CAMERA
	CELLPHONE_CAMERA_FOCUS_LOCK,// INPUT_CELLPHONE_CAMERA_FOCUS_LOCK
	CELLPHONE_CAMERA_SELFIE ,// INPUT_CELLPHONE_CAMERA_SELFIE 
	CELLPHONE_CAMERA_EXPRESSION,// INPUT_CELLPHONE_CAMERA_EXPRESSION
	CELLPHONE_CAMERA_GRID,// INPUT_CELLPHONE_CAMERA_GRID
	CELLPHONE_CAMERA_DOF,// INPUT_CELLPHONE_CAMERA_DOF
	CELLPHONE_CAMERA_FOCUS_LOCK,// INPUT_CELLPHONE_CAMERA_FOCUS_LOCK
];
