pub const CATEGORY: &'static str = &"CELLPHONE_CAMERA";
pub const CELLPHONE_CAMERA_SELFIE : &'static str = &"INPUT_CELLPHONE_CAMERA_SELFIE ";
pub const CELLPHONE_CAMERA_EXPRESSION: &'static str = &"INPUT_CELLPHONE_CAMERA_EXPRESSION";
pub const CELLPHONE_CAMERA_GRID: &'static str = &"INPUT_CELLPHONE_CAMERA_GRID";
pub const CELLPHONE_CAMERA_DOF: &'static str = &"INPUT_CELLPHONE_CAMERA_DOF";
pub const CELLPHONE_CAMERA_FOCUS_LOCK: &'static str = &"INPUT_CELLPHONE_CAMERA_FOCUS_LOCK";
