pub const CATEGORY: &'static str = &"CELLPHONE_MOVE";
pub const CELLPHONE_UP: &'static str = &"INPUT_CELLPHONE_UP";
pub const CELLPHONE_DOWN: &'static str = &"INPUT_CELLPHONE_DOWN";
pub const CELLPHONE_LEFT: &'static str = &"INPUT_CELLPHONE_LEFT";
pub const CELLPHONE_RIGHT: &'static str = &"INPUT_CELLPHONE_RIGHT";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // CELLPHONE_MOVE
	CELLPHONE_RIGHT,// INPUT_CELLPHONE_RIGHT
	CELLPHONE_UP,// INPUT_CELLPHONE_UP
	CELLPHONE_DOWN,// INPUT_CELLPHONE_DOWN
	CELLPHONE_LEFT,// INPUT_CELLPHONE_LEFT
	CELLPHONE_RIGHT,// INPUT_CELLPHONE_RIGHT
];
