pub const CATEGORY: &'static str = &"CREATOR";
pub const CREATOR_ALT_MENU_ENTRY: &'static str = &"INPUT_CREATOR_ALT_MENU_ENTRY";
pub const CREATOR_MENU_ACCEPT: &'static str = &"INPUT_CREATOR_MENU_ACCEPT";
pub const CREATOR_MENU_CANCEL: &'static str = &"INPUT_CREATOR_MENU_CANCEL";
pub const CREATOR_MENU_UP: &'static str = &"INPUT_CREATOR_MENU_UP";
pub const CREATOR_MENU_DOWN: &'static str = &"INPUT_CREATOR_MENU_DOWN";
pub const CREATOR_MENU_DELETE: &'static str = &"INPUT_CREATOR_MENU_DELETE";
pub const CREATOR_EXTRA_OPTIONS1: &'static str = &"INPUT_CREATOR_EXTRA_OPTIONS1";
pub const CREATOR_TAB_LEFT: &'static str = &"INPUT_CREATOR_TAB_LEFT";
pub const CREATOR_TAB_RIGHT: &'static str = &"INPUT_CREATOR_TAB_RIGHT";
pub const CREATOR_CONTEXT_MENU: &'static str = &"INPUT_CREATOR_CONTEXT_MENU";
pub const CREATOR_TOGGLE_DESCRIPTIONS: &'static str = &"INPUT_CREATOR_TOGGLE_DESCRIPTIONS";
pub const CREATOR_LIST: &'static str = &"INPUT_CREATOR_LIST";
pub const CREATOR_SWITCH_CAMERA: &'static str = &"INPUT_CREATOR_SWITCH_CAMERA";
pub const CREATOR_TOGGLE_ORBIT_CAMERA: &'static str = &"INPUT_CREATOR_TOGGLE_ORBIT_CAMERA";
pub const CREATOR_FAST_ZOOM: &'static str = &"INPUT_CREATOR_FAST_ZOOM";
pub const CREATOR_CAMERA_DECREASE: &'static str = &"INPUT_CREATOR_CAMERA_DECREASE";
pub const CREATOR_CAMERA_INCREASE: &'static str = &"INPUT_CREATOR_CAMERA_INCREASE";
pub const CREATOR_FOV_INCREASE: &'static str = &"INPUT_CREATOR_FOV_INCREASE";
pub const CREATOR_FOV_DECREASE: &'static str = &"INPUT_CREATOR_FOV_DECREASE";
pub const CREATOR_RESET_FOV: &'static str = &"INPUT_CREATOR_RESET_FOV";
pub const CREATOR_FAST_ADJUST: &'static str = &"INPUT_CREATOR_FAST_ADJUST";
pub const CREATOR_FINE_ADJUST: &'static str = &"INPUT_CREATOR_FINE_ADJUST";
pub const CREATOR_WARP_AND_EDIT: &'static str = &"INPUT_CREATOR_WARP_AND_EDIT";
pub const CREATOR_ROTATE_LEFT: &'static str = &"INPUT_CREATOR_ROTATE_LEFT";
pub const CREATOR_ROTATE_RIGHT: &'static str = &"INPUT_CREATOR_ROTATE_RIGHT";
pub const CREATOR_ADJUST_LEFT: &'static str = &"INPUT_CREATOR_ADJUST_LEFT";
pub const CREATOR_ADJUST_RIGHT: &'static str = &"INPUT_CREATOR_ADJUST_RIGHT";
pub const CREATOR_ENTITY_RAISE: &'static str = &"INPUT_CREATOR_ENTITY_RAISE";
pub const CREATOR_ENTITY_LOWER: &'static str = &"INPUT_CREATOR_ENTITY_LOWER";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // CREATOR
	CREATOR_ENTITY_LOWER,// INPUT_CREATOR_ENTITY_LOWER
	CREATOR_ALT_MENU_ENTRY,// INPUT_CREATOR_ALT_MENU_ENTRY
	CREATOR_MENU_ACCEPT,// INPUT_CREATOR_MENU_ACCEPT
	CREATOR_MENU_CANCEL,// INPUT_CREATOR_MENU_CANCEL
	CREATOR_MENU_UP,// INPUT_CREATOR_MENU_UP
	CREATOR_MENU_DOWN,// INPUT_CREATOR_MENU_DOWN
	CREATOR_MENU_DELETE,// INPUT_CREATOR_MENU_DELETE
	CREATOR_EXTRA_OPTIONS1,// INPUT_CREATOR_EXTRA_OPTIONS1
	CREATOR_TAB_LEFT,// INPUT_CREATOR_TAB_LEFT
	CREATOR_TAB_RIGHT,// INPUT_CREATOR_TAB_RIGHT
	CREATOR_CONTEXT_MENU,// INPUT_CREATOR_CONTEXT_MENU
	CREATOR_TOGGLE_DESCRIPTIONS,// INPUT_CREATOR_TOGGLE_DESCRIPTIONS
	CREATOR_LIST,// INPUT_CREATOR_LIST
	CREATOR_SWITCH_CAMERA,// INPUT_CREATOR_SWITCH_CAMERA
	CREATOR_TOGGLE_ORBIT_CAMERA,// INPUT_CREATOR_TOGGLE_ORBIT_CAMERA
	CREATOR_FAST_ZOOM,// INPUT_CREATOR_FAST_ZOOM
	CREATOR_CAMERA_DECREASE,// INPUT_CREATOR_CAMERA_DECREASE
	CREATOR_CAMERA_INCREASE,// INPUT_CREATOR_CAMERA_INCREASE
	CREATOR_FOV_INCREASE,// INPUT_CREATOR_FOV_INCREASE
	CREATOR_FOV_DECREASE,// INPUT_CREATOR_FOV_DECREASE
	CREATOR_RESET_FOV,// INPUT_CREATOR_RESET_FOV
	CREATOR_FAST_ADJUST,// INPUT_CREATOR_FAST_ADJUST
	CREATOR_FINE_ADJUST,// INPUT_CREATOR_FINE_ADJUST
	CREATOR_WARP_AND_EDIT,// INPUT_CREATOR_WARP_AND_EDIT
	CREATOR_ROTATE_LEFT,// INPUT_CREATOR_ROTATE_LEFT
	CREATOR_ROTATE_RIGHT,// INPUT_CREATOR_ROTATE_RIGHT
	CREATOR_ADJUST_LEFT,// INPUT_CREATOR_ADJUST_LEFT
	CREATOR_ADJUST_RIGHT,// INPUT_CREATOR_ADJUST_RIGHT
	CREATOR_ENTITY_RAISE,// INPUT_CREATOR_ENTITY_RAISE
	CREATOR_ENTITY_LOWER,// INPUT_CREATOR_ENTITY_LOWER
];
