pub const CATEGORY: &'static str = &"ENDSCREEN";
pub const FRONTEND_ENDSCREEN_ACCEPT: &'static str = &"INPUT_FRONTEND_ENDSCREEN_ACCEPT";
pub const FRONTEND_ENDSCREEN_EXPAND: &'static str = &"INPUT_FRONTEND_ENDSCREEN_EXPAND";
