pub const CATEGORY: &'static str = &"FRONTEND";
pub const FRONTEND_DOWN: &'static str = &"INPUT_FRONTEND_DOWN";
pub const FRONTEND_UP: &'static str = &"INPUT_FRONTEND_UP";
pub const FRONTEND_LEFT: &'static str = &"INPUT_FRONTEND_LEFT";
pub const FRONTEND_RIGHT: &'static str = &"INPUT_FRONTEND_RIGHT";
pub const FRONTEND_RDOWN: &'static str = &"INPUT_FRONTEND_RDOWN";
pub const FRONTEND_RUP: &'static str = &"INPUT_FRONTEND_RUP";
pub const FRONTEND_RLEFT: &'static str = &"INPUT_FRONTEND_RLEFT";
pub const FRONTEND_RRIGHT: &'static str = &"INPUT_FRONTEND_RRIGHT";
pub const FRONTEND_AXIS_X: &'static str = &"INPUT_FRONTEND_AXIS_X";
pub const FRONTEND_AXIS_Y: &'static str = &"INPUT_FRONTEND_AXIS_Y";
pub const FRONTEND_RIGHT_AXIS_X: &'static str = &"INPUT_FRONTEND_RIGHT_AXIS_X";
pub const FRONTEND_RIGHT_AXIS_Y: &'static str = &"INPUT_FRONTEND_RIGHT_AXIS_Y";
pub const FRONTEND_ACCEPT: &'static str = &"INPUT_FRONTEND_ACCEPT";
pub const FRONTEND_CANCEL: &'static str = &"INPUT_FRONTEND_CANCEL";
pub const FRONTEND_X: &'static str = &"INPUT_FRONTEND_X";
pub const FRONTEND_Y: &'static str = &"INPUT_FRONTEND_Y";
pub const FRONTEND_LB: &'static str = &"INPUT_FRONTEND_LB";
pub const FRONTEND_RB: &'static str = &"INPUT_FRONTEND_RB";
pub const FRONTEND_LT: &'static str = &"INPUT_FRONTEND_LT";
pub const FRONTEND_RT: &'static str = &"INPUT_FRONTEND_RT";
pub const FRONTEND_LS: &'static str = &"INPUT_FRONTEND_LS";
pub const FRONTEND_RS: &'static str = &"INPUT_FRONTEND_RS";
pub const FRONTEND_LEADERBOARD: &'static str = &"INPUT_FRONTEND_LEADERBOARD";
pub const FRONTEND_SELECT: &'static str = &"INPUT_FRONTEND_SELECT";
pub const FRONTEND_DELETE: &'static str = &"INPUT_FRONTEND_DELETE";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // FRONTEND
	FRONTEND_DELETE,// INPUT_FRONTEND_DELETE
	FRONTEND_DOWN,// INPUT_FRONTEND_DOWN
	FRONTEND_UP,// INPUT_FRONTEND_UP
	FRONTEND_LEFT,// INPUT_FRONTEND_LEFT
	FRONTEND_RIGHT,// INPUT_FRONTEND_RIGHT
	FRONTEND_RDOWN,// INPUT_FRONTEND_RDOWN
	FRONTEND_RUP,// INPUT_FRONTEND_RUP
	FRONTEND_RLEFT,// INPUT_FRONTEND_RLEFT
	FRONTEND_RRIGHT,// INPUT_FRONTEND_RRIGHT
	FRONTEND_AXIS_X,// INPUT_FRONTEND_AXIS_X
	FRONTEND_AXIS_Y,// INPUT_FRONTEND_AXIS_Y
	FRONTEND_RIGHT_AXIS_X,// INPUT_FRONTEND_RIGHT_AXIS_X
	FRONTEND_RIGHT_AXIS_Y,// INPUT_FRONTEND_RIGHT_AXIS_Y
	FRONTEND_ACCEPT,// INPUT_FRONTEND_ACCEPT
	FRONTEND_CANCEL,// INPUT_FRONTEND_CANCEL
	FRONTEND_X,// INPUT_FRONTEND_X
	FRONTEND_Y,// INPUT_FRONTEND_Y
	FRONTEND_LB,// INPUT_FRONTEND_LB
	FRONTEND_RB,// INPUT_FRONTEND_RB
	FRONTEND_LT,// INPUT_FRONTEND_LT
	FRONTEND_RT,// INPUT_FRONTEND_RT
	FRONTEND_LS,// INPUT_FRONTEND_LS
	FRONTEND_RS,// INPUT_FRONTEND_RS
	FRONTEND_LEADERBOARD,// INPUT_FRONTEND_LEADERBOARD
	FRONTEND_SELECT,// INPUT_FRONTEND_SELECT
	FRONTEND_DELETE,// INPUT_FRONTEND_DELETE
];
