pub const CATEGORY: &'static str = &"GENERAL";
pub const HUD_SPECIAL: &'static str = &"INPUT_HUD_SPECIAL";
pub const SPECIAL_ABILITY_PC: &'static str = &"INPUT_SPECIAL_ABILITY_PC";
pub const CHARACTER_WHEEL: &'static str = &"INPUT_CHARACTER_WHEEL";
pub const SELECT_CHARACTER_MICHAEL: &'static str = &"INPUT_SELECT_CHARACTER_MICHAEL";
pub const SELECT_CHARACTER_FRANKLIN: &'static str = &"INPUT_SELECT_CHARACTER_FRANKLIN";
pub const SELECT_CHARACTER_TREVOR: &'static str = &"INPUT_SELECT_CHARACTER_TREVOR";
pub const SELECT_CHARACTER_MULTIPLAYER: &'static str = &"INPUT_SELECT_CHARACTER_MULTIPLAYER";
pub const INTERACTION_MENU: &'static str = &"INPUT_INTERACTION_MENU";
pub const REPLAY_START_STOP_RECORDING: &'static str = &"INPUT_REPLAY_START_STOP_RECORDING";
pub const REPLAY_START_STOP_RECORDING_SECONDARY: &'static str = &"INPUT_REPLAY_START_STOP_RECORDING_SECONDARY";
pub const SAVE_REPLAY_CLIP: &'static str = &"INPUT_SAVE_REPLAY_CLIP";
pub const FRONTEND_SOCIAL_CLUB_SECONDARY: &'static str = &"INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // GENERAL
	FRONTEND_SOCIAL_CLUB_SECONDARY,// INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY
	HUD_SPECIAL,// INPUT_HUD_SPECIAL
	SPECIAL_ABILITY_PC,// INPUT_SPECIAL_ABILITY_PC
	CHARACTER_WHEEL,// INPUT_CHARACTER_WHEEL
	SELECT_CHARACTER_MICHAEL,// INPUT_SELECT_CHARACTER_MICHAEL
	SELECT_CHARACTER_FRANKLIN,// INPUT_SELECT_CHARACTER_FRANKLIN
	SELECT_CHARACTER_TREVOR,// INPUT_SELECT_CHARACTER_TREVOR
	SELECT_CHARACTER_MULTIPLAYER,// INPUT_SELECT_CHARACTER_MULTIPLAYER
	INTERACTION_MENU,// INPUT_INTERACTION_MENU
	REPLAY_START_STOP_RECORDING,// INPUT_REPLAY_START_STOP_RECORDING
	REPLAY_START_STOP_RECORDING_SECONDARY,// INPUT_REPLAY_START_STOP_RECORDING_SECONDARY
	SAVE_REPLAY_CLIP,// INPUT_SAVE_REPLAY_CLIP
	FRONTEND_SOCIAL_CLUB_SECONDARY,// INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY
];
