pub const CATEGORY: &'static str = &"IGNORE";
pub const ACCURATE_AIM: &'static str = &"INPUT_ACCURATE_AIM";
pub const CURSOR_CANCEL: &'static str = &"INPUT_CURSOR_CANCEL";
pub const CURSOR_SCROLL_UP: &'static str = &"INPUT_CURSOR_SCROLL_UP";
pub const CURSOR_SCROLL_DOWN: &'static str = &"INPUT_CURSOR_SCROLL_DOWN";
pub const LOOK_LR: &'static str = &"INPUT_LOOK_LR";
pub const LOOK_UD: &'static str = &"INPUT_LOOK_UD";
pub const LOOK_UP_ONLY: &'static str = &"INPUT_LOOK_UP_ONLY";
pub const LOOK_DOWN_ONLY: &'static str = &"INPUT_LOOK_DOWN_ONLY";
pub const LOOK_LEFT_ONLY: &'static str = &"INPUT_LOOK_LEFT_ONLY";
pub const LOOK_RIGHT_ONLY: &'static str = &"INPUT_LOOK_RIGHT_ONLY";
pub const SCRIPTED_FLY_UD: &'static str = &"INPUT_SCRIPTED_FLY_UD";
pub const SCRIPTED_FLY_LR: &'static str = &"INPUT_SCRIPTED_FLY_LR";
pub const SCRIPTED_FLY_ZUP: &'static str = &"INPUT_SCRIPTED_FLY_ZUP";
pub const SCRIPTED_FLY_ZDOWN: &'static str = &"INPUT_SCRIPTED_FLY_ZDOWN";
pub const WEAPON_WHEEL_UD: &'static str = &"INPUT_WEAPON_WHEEL_UD";
pub const WEAPON_WHEEL_LR: &'static str = &"INPUT_WEAPON_WHEEL_LR";
pub const RADIO_WHEEL_UD: &'static str = &"INPUT_RADIO_WHEEL_UD";
pub const RADIO_WHEEL_LR: &'static str = &"INPUT_RADIO_WHEEL_LR";
pub const SKIP_CUTSCENE: &'static str = &"INPUT_SKIP_CUTSCENE";
pub const VEH_CINEMATIC_UD: &'static str = &"INPUT_VEH_CINEMATIC_UD";
pub const VEH_CINEMATIC_UP_ONLY: &'static str = &"INPUT_VEH_CINEMATIC_UP_ONLY";
pub const VEH_CINEMATIC_DOWN_ONLY: &'static str = &"INPUT_VEH_CINEMATIC_DOWN_ONLY";
pub const VEH_SLOWMO_UD: &'static str = &"INPUT_VEH_SLOWMO_UD";
pub const VEH_CINEMATIC_LR: &'static str = &"INPUT_VEH_CINEMATIC_LR";
pub const MAP_POI: &'static str = &"INPUT_MAP_POI";
pub const SCRIPT_LEFT_AXIS_X: &'static str = &"INPUT_SCRIPT_LEFT_AXIS_X";
pub const SCRIPT_LEFT_AXIS_Y: &'static str = &"INPUT_SCRIPT_LEFT_AXIS_Y";
pub const SCRIPT_RIGHT_AXIS_X: &'static str = &"INPUT_SCRIPT_RIGHT_AXIS_X";
pub const SCRIPT_RIGHT_AXIS_Y: &'static str = &"INPUT_SCRIPT_RIGHT_AXIS_Y";
pub const SCRIPT_RUP: &'static str = &"INPUT_SCRIPT_RUP";
pub const SCRIPT_RDOWN: &'static str = &"INPUT_SCRIPT_RDOWN";
pub const SCRIPT_RLEFT: &'static str = &"INPUT_SCRIPT_RLEFT";
pub const SCRIPT_RRIGHT: &'static str = &"INPUT_SCRIPT_RRIGHT";
pub const SCRIPT_LB: &'static str = &"INPUT_SCRIPT_LB";
pub const SCRIPT_RB: &'static str = &"INPUT_SCRIPT_RB";
pub const SCRIPT_LT: &'static str = &"INPUT_SCRIPT_LT";
pub const SCRIPT_RT: &'static str = &"INPUT_SCRIPT_RT";
pub const SCRIPT_LS: &'static str = &"INPUT_SCRIPT_LS";
pub const SCRIPT_RS: &'static str = &"INPUT_SCRIPT_RS";
pub const SCRIPT_PAD_UP: &'static str = &"INPUT_SCRIPT_PAD_UP";
pub const SCRIPT_PAD_DOWN: &'static str = &"INPUT_SCRIPT_PAD_DOWN";
pub const SCRIPT_PAD_LEFT: &'static str = &"INPUT_SCRIPT_PAD_LEFT";
pub const SCRIPT_PAD_RIGHT: &'static str = &"INPUT_SCRIPT_PAD_RIGHT";
pub const SCRIPT_SELECT: &'static str = &"INPUT_SCRIPT_SELECT";
pub const SCALED_LOOK_LR: &'static str = &"INPUT_SCALED_LOOK_LR";
pub const SCALED_LOOK_UD: &'static str = &"INPUT_SCALED_LOOK_UD";
pub const SCALED_LOOK_UP_ONLY: &'static str = &"INPUT_SCALED_LOOK_UP_ONLY";
pub const SCALED_LOOK_DOWN_ONLY: &'static str = &"INPUT_SCALED_LOOK_DOWN_ONLY";
pub const SCALED_LOOK_LEFT_ONLY: &'static str = &"INPUT_SCALED_LOOK_LEFT_ONLY";
pub const SCALED_LOOK_RIGHT_ONLY: &'static str = &"INPUT_SCALED_LOOK_RIGHT_ONLY";
pub const REPLAY_MARKER_DELETE: &'static str = &"INPUT_REPLAY_MARKER_DELETE";
pub const REPLAY_CLIP_DELETE: &'static str = &"INPUT_REPLAY_CLIP_DELETE";
pub const REPLAY_PAUSE: &'static str = &"INPUT_REPLAY_PAUSE";
pub const REPLAY_REWIND: &'static str = &"INPUT_REPLAY_REWIND";
pub const REPLAY_FFWD: &'static str = &"INPUT_REPLAY_FFWD";
pub const REPLAY_NEWMARKER: &'static str = &"INPUT_REPLAY_NEWMARKER";
pub const REPLAY_RECORD: &'static str = &"INPUT_REPLAY_RECORD";
pub const REPLAY_SCREENSHOT: &'static str = &"INPUT_REPLAY_SCREENSHOT";
pub const REPLAY_HIDEHUD: &'static str = &"INPUT_REPLAY_HIDEHUD";
pub const REPLAY_STARTPOINT: &'static str = &"INPUT_REPLAY_STARTPOINT";
pub const REPLAY_ENDPOINT: &'static str = &"INPUT_REPLAY_ENDPOINT";
pub const REPLAY_ADVANCE: &'static str = &"INPUT_REPLAY_ADVANCE";
pub const REPLAY_BACK: &'static str = &"INPUT_REPLAY_BACK";
pub const REPLAY_TOOLS: &'static str = &"INPUT_REPLAY_TOOLS";
pub const REPLAY_RESTART: &'static str = &"INPUT_REPLAY_RESTART";
pub const REPLAY_SHOWHOTKEY: &'static str = &"INPUT_REPLAY_SHOWHOTKEY";
pub const REPLAY_CYCLEMARKERLEFT: &'static str = &"INPUT_REPLAY_CYCLEMARKERLEFT";
pub const REPLAY_CYCLEMARKERRIGHT: &'static str = &"INPUT_REPLAY_CYCLEMARKERRIGHT";
pub const REPLAY_FOVINCREASE: &'static str = &"INPUT_REPLAY_FOVINCREASE";
pub const REPLAY_FOVDECREASE: &'static str = &"INPUT_REPLAY_FOVDECREASE";
pub const REPLAY_CAMERAUP: &'static str = &"INPUT_REPLAY_CAMERAUP";
pub const REPLAY_CAMERADOWN: &'static str = &"INPUT_REPLAY_CAMERADOWN";
pub const REPLAY_SAVE: &'static str = &"INPUT_REPLAY_SAVE";
pub const REPLAY_TOGGLETIME: &'static str = &"INPUT_REPLAY_TOGGLETIME";
pub const REPLAY_TOGGLETIPS: &'static str = &"INPUT_REPLAY_TOGGLETIPS";
pub const REPLAY_PREVIEW: &'static str = &"INPUT_REPLAY_PREVIEW";
pub const CURSOR_ACCEPT: &'static str = &"INPUT_CURSOR_ACCEPT";
pub const CURSOR_X: &'static str = &"INPUT_CURSOR_X";
pub const CURSOR_Y: &'static str = &"INPUT_CURSOR_Y";
pub const REPLAY_TOGGLE_TIMELINE: &'static str = &"INPUT_REPLAY_TOGGLE_TIMELINE";
pub const REPLAY_TIMELINE_PICKUP_CLIP: &'static str = &"INPUT_REPLAY_TIMELINE_PICKUP_CLIP";
pub const REPLAY_TIMELINE_DUPLICATE_CLIP: &'static str = &"INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP";
pub const REPLAY_TIMELINE_PLACE_CLIP: &'static str = &"INPUT_REPLAY_TIMELINE_PLACE_CLIP";
pub const REPLAY_CTRL: &'static str = &"INPUT_REPLAY_CTRL";
pub const REPLAY_TIMELINE_SAVE: &'static str = &"INPUT_REPLAY_TIMELINE_SAVE";
pub const REPLAY_PREVIEW_AUDIO: &'static str = &"INPUT_REPLAY_PREVIEW_AUDIO";
pub const CREATOR_LS: &'static str = &"INPUT_CREATOR_LS";
pub const CREATOR_RS: &'static str = &"INPUT_CREATOR_RS";
pub const CREATOR_LT: &'static str = &"INPUT_CREATOR_LT";
pub const CREATOR_RT: &'static str = &"INPUT_CREATOR_RT";
pub const CREATOR_MENU_TOGGLE: &'static str = &"INPUT_CREATOR_MENU_TOGGLE";
pub const CREATOR_ACCEPT: &'static str = &"INPUT_CREATOR_ACCEPT";
pub const CREATOR_DELETE: &'static str = &"INPUT_CREATOR_DELETE";
pub const REPLAY_SNAPMATIC_PHOTO: &'static str = &"INPUT_REPLAY_SNAPMATIC_PHOTO";
pub const RESPAWN_FASTER: &'static str = &"INPUT_RESPAWN_FASTER";
pub const HUDMARKER_SELECT: &'static str = &"INPUT_HUDMARKER_SELECT";
pub const VEH_FLY_VERTICAL_FLIGHT_MODE: &'static str = &"INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE";
pub const VEH_JUMP: &'static str = &"INPUT_VEH_JUMP";
pub const DIVE: &'static str = &"INPUT_DIVE";
pub const VEH_ROOF: &'static str = &"INPUT_VEH_ROOF";
pub const VEH_PASSENGER_AIM: &'static str = &"INPUT_VEH_PASSENGER_AIM";
pub const VEH_PASSENGER_ATTACK: &'static str = &"INPUT_VEH_PASSENGER_ATTACK";
pub const VEH_SHUFFLE: &'static str = &"INPUT_VEH_SHUFFLE";
pub const MELEE_ATTACK_ALTERNATE: &'static str = &"INPUT_MELEE_ATTACK_ALTERNATE";
pub const SNIPER_ZOOM_IN_SECONDARY: &'static str = &"INPUT_SNIPER_ZOOM_IN_SECONDARY";
pub const SNIPER_ZOOM_OUT_SECONDARY: &'static str = &"INPUT_SNIPER_ZOOM_OUT_SECONDARY";
pub const VEH_PUSHBIKE_PEDAL: &'static str = &"INPUT_VEH_PUSHBIKE_PEDAL";
pub const PICKUP: &'static str = &"INPUT_PICKUP";
pub const TALK: &'static str = &"INPUT_TALK";
pub const VEH_PUSHBIKE_REAR_BRAKE: &'static str = &"INPUT_VEH_PUSHBIKE_REAR_BRAKE";
pub const THROW_GRENADE: &'static str = &"INPUT_THROW_GRENADE";
pub const VEH_FLY_DUCK: &'static str = &"INPUT_VEH_FLY_DUCK";
pub const VEH_DROP_PROJECTILE: &'static str = &"INPUT_VEH_DROP_PROJECTILE";
pub const VEH_FLY_SELECT_NEXT_WEAPON: &'static str = &"INPUT_VEH_FLY_SELECT_NEXT_WEAPON";
pub const VEH_FLY_SELECT_PREV_WEAPON: &'static str = &"INPUT_VEH_FLY_SELECT_PREV_WEAPON";
pub const MULTIPLAYER_INFO: &'static str = &"INPUT_MULTIPLAYER_INFO";
pub const CONTEXT_SECONDARY: &'static str = &"INPUT_CONTEXT_SECONDARY";
pub const QUAD_LOCO_REVERSE: &'static str = &"INPUT_QUAD_LOCO_REVERSE";
pub const SNIPER_ZOOM: &'static str = &"INPUT_SNIPER_ZOOM";
pub const MOVE_LR: &'static str = &"INPUT_MOVE_LR";
pub const MOVE_UD: &'static str = &"INPUT_MOVE_UD";
pub const VEH_MOVE_LR: &'static str = &"INPUT_VEH_MOVE_LR";
pub const VEH_MOVE_UD: &'static str = &"INPUT_VEH_MOVE_UD";
pub const VEH_FLY_ROLL_LR: &'static str = &"INPUT_VEH_FLY_ROLL_LR";
pub const VEH_FLY_PITCH_UD: &'static str = &"INPUT_VEH_FLY_PITCH_UD";
pub const VEH_SUB_TURN_LR: &'static str = &"INPUT_VEH_SUB_TURN_LR";
pub const VEH_SUB_PITCH_UD: &'static str = &"INPUT_VEH_SUB_PITCH_UD";
pub const PARACHUTE_TURN_LR: &'static str = &"INPUT_PARACHUTE_TURN_LR";
pub const PARACHUTE_PITCH_UD: &'static str = &"INPUT_PARACHUTE_PITCH_UD";
pub const CREATOR_MOVE_UD: &'static str = &"INPUT_CREATOR_MOVE_UD";
pub const CREATOR_MOVE_LR: &'static str = &"INPUT_CREATOR_MOVE_LR";
pub const SPECIAL_ABILITY: &'static str = &"INPUT_SPECIAL_ABILITY";
pub const SNIPER_ZOOM_IN_ALTERNATE: &'static str = &"INPUT_SNIPER_ZOOM_IN_ALTERNATE";
pub const SNIPER_ZOOM_OUT_ALTERNATE: &'static str = &"INPUT_SNIPER_ZOOM_OUT_ALTERNATE";
pub const CREATOR_EXTRA_OPTIONS2: &'static str = &"INPUT_CREATOR_EXTRA_OPTIONS2";
pub const WEAPON_SPECIAL: &'static str = &"INPUT_WEAPON_SPECIAL";
pub const ARREST: &'static str = &"INPUT_ARREST";
pub const VEH_SPECIAL: &'static str = &"INPUT_VEH_SPECIAL";
pub const VEH_GUN_LR: &'static str = &"INPUT_VEH_GUN_LR";
pub const VEH_GUN_UD: &'static str = &"INPUT_VEH_GUN_UD";
pub const VEH_ATTACK2: &'static str = &"INPUT_VEH_ATTACK2";
pub const VEH_HOTWIRE_LEFT: &'static str = &"INPUT_VEH_HOTWIRE_LEFT";
pub const VEH_HOTWIRE_RIGHT: &'static str = &"INPUT_VEH_HOTWIRE_RIGHT";
pub const VEH_SPECIAL_ABILITY_FRANKLIN: &'static str = &"INPUT_VEH_SPECIAL_ABILITY_FRANKLIN";
pub const VEH_STUNT_UD: &'static str = &"INPUT_VEH_STUNT_UD";
pub const MAP: &'static str = &"INPUT_MAP";
pub const ATTACK2: &'static str = &"INPUT_ATTACK2";
pub const RAPPEL_JUMP: &'static str = &"INPUT_RAPPEL_JUMP";
pub const RAPPEL_LONG_JUMP: &'static str = &"INPUT_RAPPEL_LONG_JUMP";
pub const RAPPEL_SMASH_WINDOW: &'static str = &"INPUT_RAPPEL_SMASH_WINDOW";
pub const MELEE_ATTACK1: &'static str = &"INPUT_MELEE_ATTACK1";
pub const MELEE_ATTACK2: &'static str = &"INPUT_MELEE_ATTACK2";
pub const WHISTLE: &'static str = &"INPUT_WHISTLE";
pub const MOVE_LEFT: &'static str = &"INPUT_MOVE_LEFT";
pub const MOVE_RIGHT: &'static str = &"INPUT_MOVE_RIGHT";
pub const MOVE_UP: &'static str = &"INPUT_MOVE_UP";
pub const MOVE_DOWN: &'static str = &"INPUT_MOVE_DOWN";
pub const LOOK_LEFT: &'static str = &"INPUT_LOOK_LEFT";
pub const LOOK_RIGHT: &'static str = &"INPUT_LOOK_RIGHT";
pub const LOOK_UP: &'static str = &"INPUT_LOOK_UP";
pub const LOOK_DOWN: &'static str = &"INPUT_LOOK_DOWN";
pub const PREV_WEAPON: &'static str = &"INPUT_PREV_WEAPON";
pub const NEXT_WEAPON: &'static str = &"INPUT_NEXT_WEAPON";
pub const SNIPER_ZOOM_IN: &'static str = &"INPUT_SNIPER_ZOOM_IN";
pub const SNIPER_ZOOM_OUT: &'static str = &"INPUT_SNIPER_ZOOM_OUT";
pub const VEH_MOVE_LEFT: &'static str = &"INPUT_VEH_MOVE_LEFT";
pub const VEH_MOVE_RIGHT: &'static str = &"INPUT_VEH_MOVE_RIGHT";
pub const VEH_MOVE_UP: &'static str = &"INPUT_VEH_MOVE_UP";
pub const VEH_MOVE_DOWN: &'static str = &"INPUT_VEH_MOVE_DOWN";
pub const VEH_GUN_LEFT: &'static str = &"INPUT_VEH_GUN_LEFT";
pub const VEH_GUN_RIGHT: &'static str = &"INPUT_VEH_GUN_RIGHT";
pub const VEH_GUN_UP: &'static str = &"INPUT_VEH_GUN_UP";
pub const VEH_GUN_DOWN: &'static str = &"INPUT_VEH_GUN_DOWN";
pub const VEH_LOOK_LEFT: &'static str = &"INPUT_VEH_LOOK_LEFT";
pub const VEH_LOOK_RIGHT: &'static str = &"INPUT_VEH_LOOK_RIGHT";
pub const MP_TEXT_CHAT_FRIENDS: &'static str = &"INPUT_MP_TEXT_CHAT_FRIENDS";
pub const MP_TEXT_CHAT_CREW: &'static str = &"INPUT_MP_TEXT_CHAT_CREW";
pub const VEH_DRIVE_LOOK: &'static str = &"INPUT_VEH_DRIVE_LOOK";
pub const VEH_DRIVE_LOOK2: &'static str = &"INPUT_VEH_DRIVE_LOOK2";
pub const VEH_FLY_ATTACK2: &'static str = &"INPUT_VEH_FLY_ATTACK2";
pub const VEH_HYDRAULICS_CONTROL_LEFT: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_LEFT";
pub const VEH_HYDRAULICS_CONTROL_RIGHT: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_RIGHT";
pub const VEH_HYDRAULICS_CONTROL_UP: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_UP";
pub const VEH_HYDRAULICS_CONTROL_DOWN: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_DOWN";
pub const VEH_HYDRAULICS_CONTROL_LR: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_LR";
pub const VEH_HYDRAULICS_CONTROL_UD: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_UD";
pub const CREATOR_MOVE_UP_ONLY: &'static str = &"INPUT_CREATOR_MOVE_UP_ONLY";
pub const CREATOR_MOVE_DOWN_ONLY: &'static str = &"INPUT_CREATOR_MOVE_DOWN_ONLY";
pub const CREATOR_MOVE_LEFT_ONLY: &'static str = &"INPUT_CREATOR_MOVE_LEFT_ONLY";
pub const CREATOR_MOVE_RIGHT_ONLY: &'static str = &"INPUT_CREATOR_MOVE_RIGHT_ONLY";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // IGNORE
	CREATOR_MOVE_RIGHT_ONLY,// INPUT_CREATOR_MOVE_RIGHT_ONLY
	ACCURATE_AIM,// INPUT_ACCURATE_AIM
	CURSOR_CANCEL,// INPUT_CURSOR_CANCEL
	CURSOR_SCROLL_UP,// INPUT_CURSOR_SCROLL_UP
	CURSOR_SCROLL_DOWN,// INPUT_CURSOR_SCROLL_DOWN
	LOOK_LR,// INPUT_LOOK_LR
	LOOK_UD,// INPUT_LOOK_UD
	LOOK_UP_ONLY,// INPUT_LOOK_UP_ONLY
	LOOK_DOWN_ONLY,// INPUT_LOOK_DOWN_ONLY
	LOOK_LEFT_ONLY,// INPUT_LOOK_LEFT_ONLY
	LOOK_RIGHT_ONLY,// INPUT_LOOK_RIGHT_ONLY
	SCRIPTED_FLY_UD,// INPUT_SCRIPTED_FLY_UD
	SCRIPTED_FLY_LR,// INPUT_SCRIPTED_FLY_LR
	SCRIPTED_FLY_ZUP,// INPUT_SCRIPTED_FLY_ZUP
	SCRIPTED_FLY_ZDOWN,// INPUT_SCRIPTED_FLY_ZDOWN
	WEAPON_WHEEL_UD,// INPUT_WEAPON_WHEEL_UD
	WEAPON_WHEEL_LR,// INPUT_WEAPON_WHEEL_LR
	RADIO_WHEEL_UD,// INPUT_RADIO_WHEEL_UD
	RADIO_WHEEL_LR,// INPUT_RADIO_WHEEL_LR
	SKIP_CUTSCENE,// INPUT_SKIP_CUTSCENE
	VEH_CINEMATIC_UD,// INPUT_VEH_CINEMATIC_UD
	VEH_CINEMATIC_UP_ONLY,// INPUT_VEH_CINEMATIC_UP_ONLY
	VEH_CINEMATIC_DOWN_ONLY,// INPUT_VEH_CINEMATIC_DOWN_ONLY
	VEH_SLOWMO_UD,// INPUT_VEH_SLOWMO_UD
	VEH_CINEMATIC_LR,// INPUT_VEH_CINEMATIC_LR
	MAP_POI,// INPUT_MAP_POI
	SCRIPT_LEFT_AXIS_X,// INPUT_SCRIPT_LEFT_AXIS_X
	SCRIPT_LEFT_AXIS_Y,// INPUT_SCRIPT_LEFT_AXIS_Y
	SCRIPT_RIGHT_AXIS_X,// INPUT_SCRIPT_RIGHT_AXIS_X
	SCRIPT_RIGHT_AXIS_Y,// INPUT_SCRIPT_RIGHT_AXIS_Y
	SCRIPT_RUP,// INPUT_SCRIPT_RUP
	SCRIPT_RDOWN,// INPUT_SCRIPT_RDOWN
	SCRIPT_RLEFT,// INPUT_SCRIPT_RLEFT
	SCRIPT_RRIGHT,// INPUT_SCRIPT_RRIGHT
	SCRIPT_LB,// INPUT_SCRIPT_LB
	SCRIPT_RB,// INPUT_SCRIPT_RB
	SCRIPT_LT,// INPUT_SCRIPT_LT
	SCRIPT_RT,// INPUT_SCRIPT_RT
	SCRIPT_LS,// INPUT_SCRIPT_LS
	SCRIPT_RS,// INPUT_SCRIPT_RS
	SCRIPT_PAD_UP,// INPUT_SCRIPT_PAD_UP
	SCRIPT_PAD_DOWN,// INPUT_SCRIPT_PAD_DOWN
	SCRIPT_PAD_LEFT,// INPUT_SCRIPT_PAD_LEFT
	SCRIPT_PAD_RIGHT,// INPUT_SCRIPT_PAD_RIGHT
	SCRIPT_SELECT,// INPUT_SCRIPT_SELECT
	SCALED_LOOK_LR,// INPUT_SCALED_LOOK_LR
	SCALED_LOOK_UD,// INPUT_SCALED_LOOK_UD
	SCALED_LOOK_UP_ONLY,// INPUT_SCALED_LOOK_UP_ONLY
	SCALED_LOOK_DOWN_ONLY,// INPUT_SCALED_LOOK_DOWN_ONLY
	SCALED_LOOK_LEFT_ONLY,// INPUT_SCALED_LOOK_LEFT_ONLY
	SCALED_LOOK_RIGHT_ONLY,// INPUT_SCALED_LOOK_RIGHT_ONLY
	REPLAY_MARKER_DELETE,// INPUT_REPLAY_MARKER_DELETE
	REPLAY_CLIP_DELETE,// INPUT_REPLAY_CLIP_DELETE
	REPLAY_PAUSE,// INPUT_REPLAY_PAUSE
	REPLAY_REWIND,// INPUT_REPLAY_REWIND
	REPLAY_FFWD,// INPUT_REPLAY_FFWD
	REPLAY_NEWMARKER,// INPUT_REPLAY_NEWMARKER
	REPLAY_RECORD,// INPUT_REPLAY_RECORD
	REPLAY_SCREENSHOT,// INPUT_REPLAY_SCREENSHOT
	REPLAY_HIDEHUD,// INPUT_REPLAY_HIDEHUD
	REPLAY_STARTPOINT,// INPUT_REPLAY_STARTPOINT
	REPLAY_ENDPOINT,// INPUT_REPLAY_ENDPOINT
	REPLAY_ADVANCE,// INPUT_REPLAY_ADVANCE
	REPLAY_BACK,// INPUT_REPLAY_BACK
	REPLAY_TOOLS,// INPUT_REPLAY_TOOLS
	REPLAY_RESTART,// INPUT_REPLAY_RESTART
	REPLAY_SHOWHOTKEY,// INPUT_REPLAY_SHOWHOTKEY
	REPLAY_CYCLEMARKERLEFT,// INPUT_REPLAY_CYCLEMARKERLEFT
	REPLAY_CYCLEMARKERRIGHT,// INPUT_REPLAY_CYCLEMARKERRIGHT
	REPLAY_FOVINCREASE,// INPUT_REPLAY_FOVINCREASE
	REPLAY_FOVDECREASE,// INPUT_REPLAY_FOVDECREASE
	REPLAY_CAMERAUP,// INPUT_REPLAY_CAMERAUP
	REPLAY_CAMERADOWN,// INPUT_REPLAY_CAMERADOWN
	REPLAY_SAVE,// INPUT_REPLAY_SAVE
	REPLAY_TOGGLETIME,// INPUT_REPLAY_TOGGLETIME
	REPLAY_TOGGLETIPS,// INPUT_REPLAY_TOGGLETIPS
	REPLAY_PREVIEW,// INPUT_REPLAY_PREVIEW
	CURSOR_ACCEPT,// INPUT_CURSOR_ACCEPT
	CURSOR_X,// INPUT_CURSOR_X
	CURSOR_Y,// INPUT_CURSOR_Y
	REPLAY_TOGGLE_TIMELINE,// INPUT_REPLAY_TOGGLE_TIMELINE
	REPLAY_TIMELINE_PICKUP_CLIP,// INPUT_REPLAY_TIMELINE_PICKUP_CLIP
	REPLAY_TIMELINE_DUPLICATE_CLIP,// INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP
	REPLAY_TIMELINE_PLACE_CLIP,// INPUT_REPLAY_TIMELINE_PLACE_CLIP
	REPLAY_CTRL,// INPUT_REPLAY_CTRL
	REPLAY_TIMELINE_SAVE,// INPUT_REPLAY_TIMELINE_SAVE
	REPLAY_PREVIEW_AUDIO,// INPUT_REPLAY_PREVIEW_AUDIO
	CREATOR_LS,// INPUT_CREATOR_LS
	CREATOR_RS,// INPUT_CREATOR_RS
	CREATOR_LT,// INPUT_CREATOR_LT
	CREATOR_RT,// INPUT_CREATOR_RT
	CREATOR_MENU_TOGGLE,// INPUT_CREATOR_MENU_TOGGLE
	CREATOR_ACCEPT,// INPUT_CREATOR_ACCEPT
	CREATOR_DELETE,// INPUT_CREATOR_DELETE
	REPLAY_SNAPMATIC_PHOTO,// INPUT_REPLAY_SNAPMATIC_PHOTO
	RESPAWN_FASTER,// INPUT_RESPAWN_FASTER
	HUDMARKER_SELECT,// INPUT_HUDMARKER_SELECT
	VEH_FLY_VERTICAL_FLIGHT_MODE,// INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE
	VEH_JUMP,// INPUT_VEH_JUMP
	DIVE,// INPUT_DIVE
	VEH_ROOF,// INPUT_VEH_ROOF
	VEH_PASSENGER_AIM,// INPUT_VEH_PASSENGER_AIM
	VEH_PASSENGER_ATTACK,// INPUT_VEH_PASSENGER_ATTACK
	VEH_SHUFFLE,// INPUT_VEH_SHUFFLE
	MELEE_ATTACK_ALTERNATE,// INPUT_MELEE_ATTACK_ALTERNATE
	SNIPER_ZOOM_IN_SECONDARY,// INPUT_SNIPER_ZOOM_IN_SECONDARY
	SNIPER_ZOOM_OUT_SECONDARY,// INPUT_SNIPER_ZOOM_OUT_SECONDARY
	VEH_PUSHBIKE_PEDAL,// INPUT_VEH_PUSHBIKE_PEDAL
	PICKUP,// INPUT_PICKUP
	TALK,// INPUT_TALK
	VEH_PUSHBIKE_REAR_BRAKE,// INPUT_VEH_PUSHBIKE_REAR_BRAKE
	THROW_GRENADE,// INPUT_THROW_GRENADE
	VEH_FLY_DUCK,// INPUT_VEH_FLY_DUCK
	VEH_DROP_PROJECTILE,// INPUT_VEH_DROP_PROJECTILE
	VEH_FLY_SELECT_NEXT_WEAPON,// INPUT_VEH_FLY_SELECT_NEXT_WEAPON
	VEH_FLY_SELECT_PREV_WEAPON,// INPUT_VEH_FLY_SELECT_PREV_WEAPON
	MULTIPLAYER_INFO,// INPUT_MULTIPLAYER_INFO
	CONTEXT_SECONDARY,// INPUT_CONTEXT_SECONDARY
	QUAD_LOCO_REVERSE,// INPUT_QUAD_LOCO_REVERSE
	SNIPER_ZOOM,// INPUT_SNIPER_ZOOM
	MOVE_LR,// INPUT_MOVE_LR
	MOVE_UD,// INPUT_MOVE_UD
	VEH_MOVE_LR,// INPUT_VEH_MOVE_LR
	VEH_MOVE_UD,// INPUT_VEH_MOVE_UD
	VEH_FLY_ROLL_LR,// INPUT_VEH_FLY_ROLL_LR
	VEH_FLY_PITCH_UD,// INPUT_VEH_FLY_PITCH_UD
	VEH_SUB_TURN_LR,// INPUT_VEH_SUB_TURN_LR
	VEH_SUB_PITCH_UD,// INPUT_VEH_SUB_PITCH_UD
	PARACHUTE_TURN_LR,// INPUT_PARACHUTE_TURN_LR
	PARACHUTE_PITCH_UD,// INPUT_PARACHUTE_PITCH_UD
	CREATOR_MOVE_UD,// INPUT_CREATOR_MOVE_UD
	CREATOR_MOVE_LR,// INPUT_CREATOR_MOVE_LR
	SPECIAL_ABILITY,// INPUT_SPECIAL_ABILITY
	SNIPER_ZOOM_IN_ALTERNATE,// INPUT_SNIPER_ZOOM_IN_ALTERNATE
	SNIPER_ZOOM_OUT_ALTERNATE,// INPUT_SNIPER_ZOOM_OUT_ALTERNATE
	CREATOR_EXTRA_OPTIONS2,// INPUT_CREATOR_EXTRA_OPTIONS2
	WEAPON_SPECIAL,// INPUT_WEAPON_SPECIAL
	ARREST,// INPUT_ARREST
	VEH_SPECIAL,// INPUT_VEH_SPECIAL
	VEH_GUN_LR,// INPUT_VEH_GUN_LR
	VEH_GUN_UD,// INPUT_VEH_GUN_UD
	VEH_ATTACK2,// INPUT_VEH_ATTACK2
	VEH_HOTWIRE_LEFT,// INPUT_VEH_HOTWIRE_LEFT
	VEH_HOTWIRE_RIGHT,// INPUT_VEH_HOTWIRE_RIGHT
	VEH_SPECIAL_ABILITY_FRANKLIN,// INPUT_VEH_SPECIAL_ABILITY_FRANKLIN
	VEH_STUNT_UD,// INPUT_VEH_STUNT_UD
	MAP,// INPUT_MAP
	ATTACK2,// INPUT_ATTACK2
	RAPPEL_JUMP,// INPUT_RAPPEL_JUMP
	RAPPEL_LONG_JUMP,// INPUT_RAPPEL_LONG_JUMP
	RAPPEL_SMASH_WINDOW,// INPUT_RAPPEL_SMASH_WINDOW
	MELEE_ATTACK1,// INPUT_MELEE_ATTACK1
	MELEE_ATTACK2,// INPUT_MELEE_ATTACK2
	WHISTLE,// INPUT_WHISTLE
	MOVE_LEFT,// INPUT_MOVE_LEFT
	MOVE_RIGHT,// INPUT_MOVE_RIGHT
	MOVE_UP,// INPUT_MOVE_UP
	MOVE_DOWN,// INPUT_MOVE_DOWN
	LOOK_LEFT,// INPUT_LOOK_LEFT
	LOOK_RIGHT,// INPUT_LOOK_RIGHT
	LOOK_UP,// INPUT_LOOK_UP
	LOOK_DOWN,// INPUT_LOOK_DOWN
	PREV_WEAPON,// INPUT_PREV_WEAPON
	NEXT_WEAPON,// INPUT_NEXT_WEAPON
	SNIPER_ZOOM_IN,// INPUT_SNIPER_ZOOM_IN
	SNIPER_ZOOM_OUT,// INPUT_SNIPER_ZOOM_OUT
	VEH_MOVE_LEFT,// INPUT_VEH_MOVE_LEFT
	VEH_MOVE_RIGHT,// INPUT_VEH_MOVE_RIGHT
	VEH_MOVE_UP,// INPUT_VEH_MOVE_UP
	VEH_MOVE_DOWN,// INPUT_VEH_MOVE_DOWN
	VEH_GUN_LEFT,// INPUT_VEH_GUN_LEFT
	VEH_GUN_RIGHT,// INPUT_VEH_GUN_RIGHT
	VEH_GUN_UP,// INPUT_VEH_GUN_UP
	VEH_GUN_DOWN,// INPUT_VEH_GUN_DOWN
	VEH_LOOK_LEFT,// INPUT_VEH_LOOK_LEFT
	VEH_LOOK_RIGHT,// INPUT_VEH_LOOK_RIGHT
	MP_TEXT_CHAT_FRIENDS,// INPUT_MP_TEXT_CHAT_FRIENDS
	MP_TEXT_CHAT_CREW,// INPUT_MP_TEXT_CHAT_CREW
	VEH_DRIVE_LOOK,// INPUT_VEH_DRIVE_LOOK
	VEH_DRIVE_LOOK2,// INPUT_VEH_DRIVE_LOOK2
	VEH_FLY_ATTACK2,// INPUT_VEH_FLY_ATTACK2
	VEH_HYDRAULICS_CONTROL_LEFT,// INPUT_VEH_HYDRAULICS_CONTROL_LEFT
	VEH_HYDRAULICS_CONTROL_RIGHT,// INPUT_VEH_HYDRAULICS_CONTROL_RIGHT
	VEH_HYDRAULICS_CONTROL_UP,// INPUT_VEH_HYDRAULICS_CONTROL_UP
	VEH_HYDRAULICS_CONTROL_DOWN,// INPUT_VEH_HYDRAULICS_CONTROL_DOWN
	VEH_HYDRAULICS_CONTROL_LR,// INPUT_VEH_HYDRAULICS_CONTROL_LR
	VEH_HYDRAULICS_CONTROL_UD,// INPUT_VEH_HYDRAULICS_CONTROL_UD
	CREATOR_MOVE_UP_ONLY,// INPUT_CREATOR_MOVE_UP_ONLY
	CREATOR_MOVE_DOWN_ONLY,// INPUT_CREATOR_MOVE_DOWN_ONLY
	CREATOR_MOVE_LEFT_ONLY,// INPUT_CREATOR_MOVE_LEFT_ONLY
	CREATOR_MOVE_RIGHT_ONLY,// INPUT_CREATOR_MOVE_RIGHT_ONLY
];
