pub const CATEGORY: &'static str = &"MULTIPLAYER_MISC";
pub const SPECIAL_ABILITY_SECONDARY: &'static str = &"INPUT_SPECIAL_ABILITY_SECONDARY";
pub const DROP_WEAPON: &'static str = &"INPUT_DROP_WEAPON";
pub const DROP_AMMO: &'static str = &"INPUT_DROP_AMMO";
pub const SWITCH_VISOR: &'static str = &"INPUT_SWITCH_VISOR";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // MULTIPLAYER_MISC
	SWITCH_VISOR,// INPUT_SWITCH_VISOR
	SPECIAL_ABILITY_SECONDARY,// INPUT_SPECIAL_ABILITY_SECONDARY
	DROP_WEAPON,// INPUT_DROP_WEAPON
	DROP_AMMO,// INPUT_DROP_AMMO
	SWITCH_VISOR,// INPUT_SWITCH_VISOR
];
