pub const CATEGORY: &'static str = &"ON_FOOT_WEAPON_SELECT";
pub const SELECT_NEXT_WEAPON: &'static str = &"INPUT_SELECT_NEXT_WEAPON";
pub const SELECT_PREV_WEAPON: &'static str = &"INPUT_SELECT_PREV_WEAPON";
pub const WEAPON_WHEEL_NEXT: &'static str = &"INPUT_WEAPON_WHEEL_NEXT";
pub const WEAPON_WHEEL_PREV: &'static str = &"INPUT_WEAPON_WHEEL_PREV";
pub const SELECT_WEAPON_UNARMED: &'static str = &"INPUT_SELECT_WEAPON_UNARMED";
pub const SELECT_WEAPON_MELEE: &'static str = &"INPUT_SELECT_WEAPON_MELEE";
pub const SELECT_WEAPON_SHOTGUN: &'static str = &"INPUT_SELECT_WEAPON_SHOTGUN";
pub const SELECT_WEAPON_HEAVY: &'static str = &"INPUT_SELECT_WEAPON_HEAVY";
pub const SELECT_WEAPON_SPECIAL: &'static str = &"INPUT_SELECT_WEAPON_SPECIAL";
pub const SELECT_WEAPON_HANDGUN: &'static str = &"INPUT_SELECT_WEAPON_HANDGUN";
pub const SELECT_WEAPON_SMG: &'static str = &"INPUT_SELECT_WEAPON_SMG";
pub const SELECT_WEAPON_AUTO_RIFLE: &'static str = &"INPUT_SELECT_WEAPON_AUTO_RIFLE";
pub const SELECT_WEAPON_SNIPER: &'static str = &"INPUT_SELECT_WEAPON_SNIPER";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // ON_FOOT_WEAPON_SELECT
	SELECT_WEAPON_SNIPER,// INPUT_SELECT_WEAPON_SNIPER
	SELECT_NEXT_WEAPON,// INPUT_SELECT_NEXT_WEAPON
	SELECT_PREV_WEAPON,// INPUT_SELECT_PREV_WEAPON
	WEAPON_WHEEL_NEXT,// INPUT_WEAPON_WHEEL_NEXT
	WEAPON_WHEEL_PREV,// INPUT_WEAPON_WHEEL_PREV
	SELECT_WEAPON_UNARMED,// INPUT_SELECT_WEAPON_UNARMED
	SELECT_WEAPON_MELEE,// INPUT_SELECT_WEAPON_MELEE
	SELECT_WEAPON_SHOTGUN,// INPUT_SELECT_WEAPON_SHOTGUN
	SELECT_WEAPON_HEAVY,// INPUT_SELECT_WEAPON_HEAVY
	SELECT_WEAPON_SPECIAL,// INPUT_SELECT_WEAPON_SPECIAL
	SELECT_WEAPON_HANDGUN,// INPUT_SELECT_WEAPON_HANDGUN
	SELECT_WEAPON_SMG,// INPUT_SELECT_WEAPON_SMG
	SELECT_WEAPON_AUTO_RIFLE,// INPUT_SELECT_WEAPON_AUTO_RIFLE
	SELECT_WEAPON_SNIPER,// INPUT_SELECT_WEAPON_SNIPER
];
