pub const CATEGORY: &'static str = &"ON_FOOT_MOVE";
pub const MOVE_UP_ONLY: &'static str = &"INPUT_MOVE_UP_ONLY";
pub const MOVE_DOWN_ONLY: &'static str = &"INPUT_MOVE_DOWN_ONLY";
pub const MOVE_LEFT_ONLY: &'static str = &"INPUT_MOVE_LEFT_ONLY";
pub const MOVE_RIGHT_ONLY: &'static str = &"INPUT_MOVE_RIGHT_ONLY";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // ON_FOOT_MOVE
	MOVE_RIGHT_ONLY,// INPUT_MOVE_RIGHT_ONLY
	MOVE_UP_ONLY,// INPUT_MOVE_UP_ONLY
	MOVE_DOWN_ONLY,// INPUT_MOVE_DOWN_ONLY
	MOVE_LEFT_ONLY,// INPUT_MOVE_LEFT_ONLY
	MOVE_RIGHT_ONLY,// INPUT_MOVE_RIGHT_ONLY
];
