pub const CATEGORY: &'static str = &"ON_FOOT_SNIPER_ZOOM";
pub const SNIPER_ZOOM_IN_ONLY: &'static str = &"INPUT_SNIPER_ZOOM_IN_ONLY";
pub const SNIPER_ZOOM_OUT_ONLY: &'static str = &"INPUT_SNIPER_ZOOM_OUT_ONLY";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // ON_FOOT_SNIPER_ZOOM
	SNIPER_ZOOM_OUT_ONLY,// INPUT_SNIPER_ZOOM_OUT_ONLY
	SNIPER_ZOOM_IN_ONLY,// INPUT_SNIPER_ZOOM_IN_ONLY
	SNIPER_ZOOM_OUT_ONLY,// INPUT_SNIPER_ZOOM_OUT_ONLY
];
