pub const CATEGORY: &'static str = &"ON_FOOT_MELEE";
pub const MELEE_ATTACK_LIGHT: &'static str = &"INPUT_MELEE_ATTACK_LIGHT";
pub const MELEE_ATTACK_HEAVY: &'static str = &"INPUT_MELEE_ATTACK_HEAVY";
pub const MELEE_BLOCK: &'static str = &"INPUT_MELEE_BLOCK";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // ON_FOOT_MELEE
	MELEE_BLOCK,// INPUT_MELEE_BLOCK
	MELEE_ATTACK_LIGHT,// INPUT_MELEE_ATTACK_LIGHT
	MELEE_ATTACK_HEAVY,// INPUT_MELEE_ATTACK_HEAVY
	MELEE_BLOCK,// INPUT_MELEE_BLOCK
];
