pub const CATEGORY: &'static str = &"PARACHUTE";
pub const PARACHUTE_PITCH_UP_ONLY: &'static str = &"INPUT_PARACHUTE_PITCH_UP_ONLY";
pub const PARACHUTE_PITCH_DOWN_ONLY: &'static str = &"INPUT_PARACHUTE_PITCH_DOWN_ONLY";
pub const PARACHUTE_TURN_LEFT_ONLY: &'static str = &"INPUT_PARACHUTE_TURN_LEFT_ONLY";
pub const PARACHUTE_TURN_RIGHT_ONLY: &'static str = &"INPUT_PARACHUTE_TURN_RIGHT_ONLY";
pub const PARACHUTE_DEPLOY: &'static str = &"INPUT_PARACHUTE_DEPLOY";
pub const PARACHUTE_DETACH: &'static str = &"INPUT_PARACHUTE_DETACH";
pub const PARACHUTE_BRAKE_LEFT: &'static str = &"INPUT_PARACHUTE_BRAKE_LEFT";
pub const PARACHUTE_BRAKE_RIGHT: &'static str = &"INPUT_PARACHUTE_BRAKE_RIGHT";
pub const PARACHUTE_PRECISION_LANDING: &'static str = &"INPUT_PARACHUTE_PRECISION_LANDING";
pub const PARACHUTE_SMOKE: &'static str = &"INPUT_PARACHUTE_SMOKE";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // PARACHUTE
	PARACHUTE_SMOKE,// INPUT_PARACHUTE_SMOKE
	PARACHUTE_PITCH_UP_ONLY,// INPUT_PARACHUTE_PITCH_UP_ONLY
	PARACHUTE_PITCH_DOWN_ONLY,// INPUT_PARACHUTE_PITCH_DOWN_ONLY
	PARACHUTE_TURN_LEFT_ONLY,// INPUT_PARACHUTE_TURN_LEFT_ONLY
	PARACHUTE_TURN_RIGHT_ONLY,// INPUT_PARACHUTE_TURN_RIGHT_ONLY
	PARACHUTE_DEPLOY,// INPUT_PARACHUTE_DEPLOY
	PARACHUTE_DETACH,// INPUT_PARACHUTE_DETACH
	PARACHUTE_BRAKE_LEFT,// INPUT_PARACHUTE_BRAKE_LEFT
	PARACHUTE_BRAKE_RIGHT,// INPUT_PARACHUTE_BRAKE_RIGHT
	PARACHUTE_PRECISION_LANDING,// INPUT_PARACHUTE_PRECISION_LANDING
	PARACHUTE_SMOKE,// INPUT_PARACHUTE_SMOKE
];
