pub const CATEGORY: &'static str = &"RESERVED";
pub const FRONTEND_SOCIAL_CLUB: &'static str = &"INPUT_FRONTEND_SOCIAL_CLUB";
pub const FRONTEND_PAUSE_ALTERNATE: &'static str = &"INPUT_FRONTEND_PAUSE_ALTERNATE";
pub const ENTER_CHEAT_CODE: &'static str = &"INPUT_ENTER_CHEAT_CODE";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // RESERVED
	ENTER_CHEAT_CODE,// INPUT_ENTER_CHEAT_CODE
	FRONTEND_SOCIAL_CLUB,// INPUT_FRONTEND_SOCIAL_CLUB
	FRONTEND_PAUSE_ALTERNATE,// INPUT_FRONTEND_PAUSE_ALTERNATE
	ENTER_CHEAT_CODE,// INPUT_ENTER_CHEAT_CODE
];
