pub const CATEGORY: &'static str = &"VEHICLE_SUB";
pub const VEH_SUB_THROTTLE_UP: &'static str = &"INPUT_VEH_SUB_THROTTLE_UP";
pub const VEH_SUB_THROTTLE_DOWN: &'static str = &"INPUT_VEH_SUB_THROTTLE_DOWN";
pub const VEH_SUB_TURN_HARD_LEFT: &'static str = &"INPUT_VEH_SUB_TURN_HARD_LEFT";
pub const VEH_SUB_TURN_HARD_RIGHT: &'static str = &"INPUT_VEH_SUB_TURN_HARD_RIGHT";
pub const VEH_SUB_TURN_LEFT_ONLY: &'static str = &"INPUT_VEH_SUB_TURN_LEFT_ONLY";
pub const VEH_SUB_TURN_RIGHT_ONLY: &'static str = &"INPUT_VEH_SUB_TURN_RIGHT_ONLY";
pub const VEH_SUB_PITCH_UP_ONLY: &'static str = &"INPUT_VEH_SUB_PITCH_UP_ONLY";
pub const VEH_SUB_PITCH_DOWN_ONLY: &'static str = &"INPUT_VEH_SUB_PITCH_DOWN_ONLY";
pub const VEH_SUB_ASCEND: &'static str = &"INPUT_VEH_SUB_ASCEND";
pub const VEH_SUB_DESCEND: &'static str = &"INPUT_VEH_SUB_DESCEND";
pub const VEH_SUB_MOUSE_CONTROL_OVERRIDE: &'static str = &"INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // VEHICLE_SUB
	VEH_SUB_MOUSE_CONTROL_OVERRIDE,// INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE
	VEH_SUB_THROTTLE_UP,// INPUT_VEH_SUB_THROTTLE_UP
	VEH_SUB_THROTTLE_DOWN,// INPUT_VEH_SUB_THROTTLE_DOWN
	VEH_SUB_TURN_HARD_LEFT,// INPUT_VEH_SUB_TURN_HARD_LEFT
	VEH_SUB_TURN_HARD_RIGHT,// INPUT_VEH_SUB_TURN_HARD_RIGHT
	VEH_SUB_TURN_LEFT_ONLY,// INPUT_VEH_SUB_TURN_LEFT_ONLY
	VEH_SUB_TURN_RIGHT_ONLY,// INPUT_VEH_SUB_TURN_RIGHT_ONLY
	VEH_SUB_PITCH_UP_ONLY,// INPUT_VEH_SUB_PITCH_UP_ONLY
	VEH_SUB_PITCH_DOWN_ONLY,// INPUT_VEH_SUB_PITCH_DOWN_ONLY
	VEH_SUB_ASCEND,// INPUT_VEH_SUB_ASCEND
	VEH_SUB_DESCEND,// INPUT_VEH_SUB_DESCEND
	VEH_SUB_MOUSE_CONTROL_OVERRIDE,// INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE
];
