pub const CATEGORY: &'static str = &"VEHICLE_GROUND_ONLINE";
pub const VEH_HYDRAULICS_CONTROL_TOGGLE: &'static str = &"INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE";
pub const VEH_MELEE_HOLD: &'static str = &"INPUT_VEH_MELEE_HOLD";
pub const VEH_MELEE_LEFT: &'static str = &"INPUT_VEH_MELEE_LEFT";
pub const VEH_MELEE_RIGHT: &'static str = &"INPUT_VEH_MELEE_RIGHT";
pub const VEH_BIKE_WINGS: &'static str = &"INPUT_VEH_BIKE_WINGS";
pub const VEH_TRANSFORM: &'static str = &"INPUT_VEH_TRANSFORM";
pub const VEH_PARACHUTE: &'static str = &"INPUT_VEH_PARACHUTE";
pub const VEH_CAR_JUMP: &'static str = &"INPUT_VEH_CAR_JUMP";
pub const VEH_ROCKET_BOOST: &'static str = &"INPUT_VEH_ROCKET_BOOST";
pub const VEH_SHIFT_GEAR_UP: &'static str = &"INPUT_VEH_SHIFT_GEAR_UP";
pub const VEH_SHIFT_GEAR_DOWN: &'static str = &"INPUT_VEH_SHIFT_GEAR_DOWN";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // VEHICLE_GROUND_ONLINE
	VEH_SHIFT_GEAR_DOWN,// INPUT_VEH_SHIFT_GEAR_DOWN
	VEH_HYDRAULICS_CONTROL_TOGGLE,// INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE
	VEH_MELEE_HOLD,// INPUT_VEH_MELEE_HOLD
	VEH_MELEE_LEFT,// INPUT_VEH_MELEE_LEFT
	VEH_MELEE_RIGHT,// INPUT_VEH_MELEE_RIGHT
	VEH_BIKE_WINGS,// INPUT_VEH_BIKE_WINGS
	VEH_TRANSFORM,// INPUT_VEH_TRANSFORM
	VEH_PARACHUTE,// INPUT_VEH_PARACHUTE
	VEH_CAR_JUMP,// INPUT_VEH_CAR_JUMP
	VEH_ROCKET_BOOST,// INPUT_VEH_ROCKET_BOOST
	VEH_SHIFT_GEAR_UP,// INPUT_VEH_SHIFT_GEAR_UP
	VEH_SHIFT_GEAR_DOWN,// INPUT_VEH_SHIFT_GEAR_DOWN
];
