pub const CATEGORY: &'static str = &"VEHICLE_GROUND";
pub const VEH_ACCELERATE: &'static str = &"INPUT_VEH_ACCELERATE";
pub const VEH_BRAKE: &'static str = &"INPUT_VEH_BRAKE";
pub const VEH_MOVE_LEFT_ONLY: &'static str = &"INPUT_VEH_MOVE_LEFT_ONLY";
pub const VEH_MOVE_RIGHT_ONLY: &'static str = &"INPUT_VEH_MOVE_RIGHT_ONLY";
pub const VEH_MOVE_UP_ONLY: &'static str = &"INPUT_VEH_MOVE_UP_ONLY";
pub const VEH_MOVE_DOWN_ONLY: &'static str = &"INPUT_VEH_MOVE_DOWN_ONLY";
pub const VEH_ATTACK: &'static str = &"INPUT_VEH_ATTACK";
pub const VEH_AIM: &'static str = &"INPUT_VEH_AIM";
pub const VEH_HANDBRAKE: &'static str = &"INPUT_VEH_HANDBRAKE";
pub const VEH_HORN: &'static str = &"INPUT_VEH_HORN";
pub const VEH_PUSHBIKE_SPRINT: &'static str = &"INPUT_VEH_PUSHBIKE_SPRINT";
pub const VEH_PUSHBIKE_FRONT_BRAKE: &'static str = &"INPUT_VEH_PUSHBIKE_FRONT_BRAKE";
pub const VEH_MOUSE_CONTROL_OVERRIDE: &'static str = &"INPUT_VEH_MOUSE_CONTROL_OVERRIDE";

pub const ALL: &'static[&'static str] = &[
	CATEGORY, // VEHICLE_GROUND
	VEH_MOUSE_CONTROL_OVERRIDE,// INPUT_VEH_MOUSE_CONTROL_OVERRIDE
	VEH_ACCELERATE,// INPUT_VEH_ACCELERATE
	VEH_BRAKE,// INPUT_VEH_BRAKE
	VEH_MOVE_LEFT_ONLY,// INPUT_VEH_MOVE_LEFT_ONLY
	VEH_MOVE_RIGHT_ONLY,// INPUT_VEH_MOVE_RIGHT_ONLY
	VEH_MOVE_UP_ONLY,// INPUT_VEH_MOVE_UP_ONLY
	VEH_MOVE_DOWN_ONLY,// INPUT_VEH_MOVE_DOWN_ONLY
	VEH_ATTACK,// INPUT_VEH_ATTACK
	VEH_AIM,// INPUT_VEH_AIM
	VEH_HANDBRAKE,// INPUT_VEH_HANDBRAKE
	VEH_HORN,// INPUT_VEH_HORN
	VEH_PUSHBIKE_SPRINT,// INPUT_VEH_PUSHBIKE_SPRINT
	VEH_PUSHBIKE_FRONT_BRAKE,// INPUT_VEH_PUSHBIKE_FRONT_BRAKE
	VEH_MOUSE_CONTROL_OVERRIDE,// INPUT_VEH_MOUSE_CONTROL_OVERRIDE
];
